### ISSUE TITLE
keep getting 401 error

### ISSUE THREAD

**Issue by ch-nour** [mailjet/mailjet-apiv3-java#100]
i'm using the example provided in Email API documentation, using my keys but i keep getting 401 error code, which is related to incorrect Api Key / API Secret Key but i'm pretty sure that my keys are correct.

**Comment by eboisgon** [comment]
Hello ch-nour, 

The most common reason people have a 401 error while using this library when they are certain to have the right keys is an error at the level of the instantiation.

This sample will search for environment variables called  MJ_APIKEY_PUBLIC and MJ_APIKEY_PRIVATE containning the keys. 

`MailjetClient client = new MailjetClient(System.getenv("MJ_APIKEY_PUBLIC"), System.getenv("MJ_APIKEY_PRIVATE"));`

This sample directly use the key in the code : 
`MailjetClient client = new MailjetClient("XXXXXXX", "YYYYYYYY");`
where XXXXXXX and YYYYYYYY are the keys. 

If this is not fixing your problem , you can contact the Mailjet support with sample of your code and they will be happy to help you resolve the problem . 

Best regards 

Emmanuel

**Comment by ch-nour** [comment]
Thanks Emmanuel It works now.
