### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by ArthurFreitas** [mailjet/mailjet-apiv3-java#101]
I'm using the version available on maven (4.1.1). One of my templates has the word "ID_AÇÃO", and when i try to get the html text using with the following code, i end up with "ID_AÃ‡ÃƒO" instead:

```
MailjetClient MAILJETCLIENT = new MailjetClient(MJ_APIKEY_PUBLIC, MJ_APIKEY_PRIVATE);
MailjetRequest request = new MailjetRequest(TemplateDetailcontent.resource, malaDireta.getTemplate());
String html = MAILJETCLIENT.get(request).getData().getJSONObject(0).getString("Html-part");
```

I already used the curl command to see if it was a problem with the api itself, but it returns the correct word, so it's probably a problem with the java api wrapper. I used the following command:

`curl -s -X GET --user "my credentials..." https://api.mailjet.com/v3/REST/campaigndraft/1123/detailcontent`

**Comment by ArthurFreitas** [comment]
I found out what happens: 

This wrapper receives the utf-8 encoded message and interprets it using the system encoding (in my case it's 'Windows-1252' because i'm using windows, i don't think linux users have the same problem...). It ends up messing up the whole String as you can see, 'ID_AÇÃO' becomes 'ID_AÃ‡ÃƒO'.

As a workaround you can decode the string using the local encoding and then rebuild the string using UTF-8:

`correctString = new String(wrongString.getBytes(), "UTF-8");`

I'm using the lastest version (4.1.1) available on maven as i said before, and i dont know if this problem have been patched on the newest versions.

**Comment by ddamyanova** [comment]
Hello @ArthurFreitas ,

We were not able to reproduce your problem even though we created both templates and campaigns from Windows computer and afterwards we run tests again on Windows computer with both JUnit and curl. Every time the string was received as expected.

How do you inspect the content you receive that is not encoded correctly? Is it possible that your IDE is not using UTF-8 encoding?

Regards,
Desislava

**Comment by mskochev** [comment]
@ArthurFreitas, please can you share more info so we can try to solve the case?
