### ISSUE TITLE
Hi, I am trying to import a json file to selenium integration on devTest where I am getting error - org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

### ISSUE THREAD

**Issue by alishajaiz** [mailjet/mailjet-apiv3-java#104]
Json -

[
   {
      "command": "open",
      "target": "https://www.google.com/",
      "value": []
   },
   {
      "command": "click",
      "target": "link=Gmail",
      "value": []
   },
   {
      "command": "click",
      "target": "link=Create an account",
      "value": []
   },
   {
      "command": "selectWindow",
      "target": "win_ser_1",
      "value": []
   },
   {
      "command": "click",
      "target": "id=firstName",
      "value": []
   },
   {
      "command": "type",
      "target": "id=firstName",
      "value": "a"
   },
   {
      "command": "type",
      "target": "id=lastName",
      "value": "j"
   },
   {
      "command": "type",
      "target": "id=username",
      "value": "aj56476578"
   },
   {
      "command": "type",
      "target": "name=Passwd",
      "value": "asdfgh"
   },
   {
      "command": "type",
      "target": "name=ConfirmPasswd",
      "value": "asdfgh"
   },
   {
      "command": "click",
      "target": "xpath=(.//*[normalize-space(text()) and normalize-space(.)='Use 8 or more characters with a mix of letters, numbers & symbols'])[1]/following::span[4]",
      "value": []
   }
]

**Comment by kmanchikov** [comment]
Hi, 

I believe this issue has been discussed and resolved on this thread ( https://github.com/mailjet/mailjet-apiv3-java/issues/84#issuecomment-400667274 ) 

Let me know if that answers your questions, as I would be glad to follow up. 

Best,

**Comment by abambova** [comment]
Hi @alishajaiz ,

I'm closing this issue as it has been answered. Please feel free to post a new issue if needed.

Regards,
Aneliya
