### ISSUE TITLE
Client raises JSONException when it receives a 4xx error

### ISSUE THREAD

**Issue by quinao** [mailjet/mailjet-apiv3-java#107]
Hello,

I'm using Mailjet API and its java wrapper to add contacts to some mailing lists on Mailjet.

I had following exception several times when executing `mailjetClient.post(request)` (or send or put or get):

> org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

By investigating a bit I found out that MailjetClient thew this Exception because Mailjet server had responded with an error code, for example 401 or 404. The response contained no data, hence the JSONException when trying to deserialize it.

The problem is, knowing that a JSONException occurred during server response' handling isn't very helpful when trying to know what's the real cause of the problem.

-> Could the MailjetClient instead throw some meaningful exception, for example MailjetException with a message saying "unauthorized" or "resource not found" or something like that?

Thanks,

quinao

**Comment by todorDim** [comment]
Hey @quinao,

Indeed this is something we're willing to implement with the next iteration of the wrapper.

Regards,
T.

**Comment by Nikola-Andreev** [comment]
Hi.
The problem was fixed and soon will be available on central maven repository, from version 4.2.1
Regards.
