### ISSUE TITLE
Publish latest version on Maven central repo

### ISSUE THREAD

**Issue by mladen-stankovic** [mailjet/mailjet-apiv3-java#109]
Please publish your latest release on maven central repo so we can use the version with fixed bugs:

https://mvnrepository.com/artifact/com.mailjet/mailjet-client

Thank you

**Comment by Nikola-Andreev** [comment]
Hi.
The latest version (4.2.0) is now published and visible in the central maven repository.
Sorry about the delay.
Regards.
