### ISSUE TITLE
Conceptual problem with this SDK

### ISSUE THREAD

**Issue by fabiocarneiro** [mailjet/mailjet-apiv3-java#112]
I want to make a point that this library is exposing the fact that we are using HTTP and JSON to communicate with Mailjet, which is something I should not care as someone implementing it.

The API I would expect would be something like:

```kotlin
val message: Message = Message(
    Recipient("john@example.com"), 
    Subject("Hello World"),
    Body("This is a message") // maybe a stream here?
)

client.send(message)
```

If it is about sending a JSON message to an endpoint, I can do that myself and this is not as useful as it could be.

I should not even be aware this is HTTP, REST, Graphql, JSON, etc...

**Comment by goacoustic** [comment]
Hi @fabiocarneiro, thanks for raising this issue.

I've added a transaction email builder to handle the most popular case, if you need to cover some other methods - please, open a new issue to track it easier.
