### ISSUE TITLE
Move ContactList from v3 to v3.1

### ISSUE THREAD

**Issue by ergunp** [mailjet/mailjet-apiv3-java#118]
Hi, seems like the contact list resource is only available when Mailjet client is set to v3. 

Is it possible to move this to v3.1? thanks

**Comment by goacoustic** [comment]
@ergunp Hi, thanks for raising this question!
It's quite a task to have a redirect on the API side, but some SDK client redesign could help. 
In PR I changed the way how API versioning is handled inside MailJet client, so when it's merged, you can just invoke the method you need without worrying about specifying the API version. 
Will it fit your request, or you have some objections/comments?

**Comment by ergunp** [comment]
@goacoustic Thanks, this is much appreciated. There is isn't a specific requirement in my case.

**Comment by goacoustic** [comment]
@ergunp Ok, cool, thank I cut the release v5.0.0 where those changes are included.
