### ISSUE TITLE
How to combine multiple filters

### ISSUE THREAD

**Issue by kaveiros** [mailjet/mailjet-apiv3-java#12]
Hi, on your documentation you say that multiple filtering can be achieved by using something like this

 ResultSet<Newsletter> newsletters = client
                .createCall(Newsletter.List)
                .filterBy(NewsletterFilter.EDITMODE, Newsletter.EditMode.HTML)
                .filterBy(NewsletterFilter.ISDELETED, false)
                .execute();

My question is : Does this mean that the results of the first filter are afterwards filtered anew by he next filter, or that there are two independent filters that are applied to the same data?

If the first case is true, then how do I  implement two independent filters at the same data in one method call?

**Comment by Gormador** [comment]
Hi @kaveiros ,

Filters used in the java wrapper work the same way as filters used in cUrl calls to the API.
They do so because filters are an API functionality and not a specific java-wrapper feature.

Also, they are all applied to the same data, not after one another.


Hope this helps.
Gaëtan

**Comment by kaveiros** [comment]
Yes it is very helpfull! Actually it solves my issues. Thank you very much @Gormador
