### ISSUE TITLE
StatusCode 400 without body using 4.5.0, working using 4.2.1

### ISSUE THREAD

**Issue by thepiwo** [mailjet/mailjet-apiv3-java#129]
Hello, I have some trouble updating the dependency from 4.2.1 to 4.5.0. I tried finding a changelog but in the end used the example from the readme to test it out.

Using 4.2.1 correctly sends the email, using 4.5.0 I receive status 400 with empty body, the sent body is the same.

```java
mailjetClient = new MailjetClient(public, secret, new ClientOptions("v3.1"))
mailjetClient.setDebug(MailjetClient.VERBOSE_DEBUG)
mailjetClient.post(new MailjetRequest(Emailv31.resource)
        .property(Emailv31.MESSAGES, new JSONArray()
          .put(new JSONObject()
            .put(Emailv31.Message.FROM, new JSONObject()
              .put("Email", "test@example.com")
              .put("Name", "Me"))
            .put(Emailv31.Message.TO, new JSONArray()
              .put(new JSONObject()
                .put("Email", "test@example.com")
                .put("Name", "You")))
            .put(Emailv31.Message.SUBJECT, "My first Mailjet Email!")
            .put(Emailv31.Message.TEXTPART, "Greetings from Mailjet!")
            .put(Emailv31.Message.HTMLPART, "<h3>Dear passenger 1, welcome to <a href=\"https://www.mailjet.com/\">Mailjet</a>!</h3><br />May the delivery force be with you!"))))
```

```
=== HTTP Request ===
POST https://api.mailjet.com/v3.1/send
Accept-Charset:UTF-8
Accept:application/json
user-agent:mailjet-apiv3-java/v4.5.0
Content-Type:application/json
=== HTTP Response ===
Receive url: https://api.mailjet.com/v3.1/send
Status: 400
date:Tue, 12 May 2020 09:25:52 GMT
null:HTTP/1.1 400 Bad Request
content-length:177
x-mj-request-guid:redacted-unkown-if-security-relevant
content-type:application/json; charset=UTF-8
Content:
null
```

**Comment by thepiwo** [comment]
I figured it out, but I keep the issue open, as I think it needs to be resolved globally.

The default timeout https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/ClientOptions.java#L16 is set so short the mailjet server has no time to respond (within 10ms). The previous default in 4.2.1. was 8000ms which works fine for me if I manually set it in 4.5.0.

**Comment by CluEleSsUK** [comment]
I have also run into this problem.  Indeed upping the timeout fixes it - why oh why does it return a 400 though in this case?!

**Comment by thepiwo** [comment]
@CluEleSsUK I am unsure why this yields a 400 as status code, in theory it is a "bad request".

**Comment by digsub** [comment]
Not sure my issue #130 is the same, but timeout issues seem to be going around.  I still get immediate:

> com.mailjet.client.errors.MailjetSocketTimeoutException: Socket Timeout

1) Using implementation 'com.mailjet:mailjet-client:4.2.1'  

or

2) implementation 'com.mailjet:mailjet-client:4.5.0' 
 
    and this added to my code...
```     

        try {
            myClientOptions = new ClientOptions("v3.1");
            myClientOptions.setTimeout(8000);

```

**Comment by thepiwo** [comment]
Yes that's the same issue I was facing

**Comment by digsub** [comment]
Ok, thanks.  I see the commit "Add read timeout" 28 days ago so maybe something else happened there.  I've tried 8000ms etc with no success.  Any other ideas?

**Comment by thepiwo** [comment]
Ah, then it's a different issue, for me `mailjet-client:4.2.1` and `myClientOptions.setTimeout(8000);` do work

**Comment by digsub** [comment]
Thanks again.  Anyway, I'll give your issue a shout out in #130.

**Comment by bknasmueller** [comment]
I had the same issue and could solve it by manually specifying a larger timeout. This pull request should fix this issue by setting a sane default: https://github.com/mailjet/mailjet-apiv3-java/pull/132

**Comment by maxixcom** [comment]
> I had the same issue and could solve it by manually specifying a larger timeout. This pull request should fix this issue by setting a sane default: #132

Yes it's great! I think it would be better to have more descriptive exception as well.

**Comment by torakiki** [comment]
Got bitten by this, spent some time debugging before I figured it was cased by the upgraded lib. Exception message and debug info are kind of useless .

**Comment by goacoustic** [comment]
@thepiwo Hi! The fix is merged and will be included in the next package release ASAP.
For now, you can the workaround mentioned with setting the timeout to 8000 in the client options, sorry about that.

@maxixcom Regarding more descriptive exception - I fully agree, have to look deeper into it.

For now closing, as the fix was merged.
