### ISSUE TITLE
.GET issue 

### ISSUE THREAD

**Issue by kaveiros** [mailjet/mailjet-apiv3-java#13]
Greetings again
I cannot implement the View part both on CampaignStatistics and ApiKeyTotals.
There is only List to be used and as such,  i cannot call .Get 
ex.
```
cl.createCall(ApiKeyTotals.Get)
  .identifiedBy(ApiKeyTotalsProperty.ID, id)
  .execute();
```
or
```
cl.createCall(CampaignStatistics.Get)
  .identifiedBy(CampaignStatisticsProperty.ID, id)
  .execute();
```

Also, they both refer to other classes, which also puzzles me as to how to do that. In the above examples, .ID in both cases does not exist, nor for the second the "customvalue" as shown in the documentation. How do i call the totals and statistics from other class instances with their ID or other stat?

Thank you in advance
Remaining yours

**Comment by Gormador** [comment]
Hi  @kaveiros,

I'm not sure of what you are trying to achieve here. Though I can answer you on one point: the `ApiKeyTotals` resource is specific to the API key pair that you are using to issue the call. A simple `.Get`  on the resource should be enough to obtain the result, as written [in the reference](https://dev.mailjet.com/email-api/v3/apikeytotals/): 
```
cl.createCall(ApiKeyTotals.Get)
  .execute();
```
Regarding the `CampaignStatistics` resource, you need to specify a `CampaignID` as, again, written in [the doc](https://dev.mailjet.com/email-api/v3/campaignstatistics/) ;-)

I would advise you to read our [guides](https://dev.mailjet.com/guides/contact-guide/) and, in particular, the part [about the API](http://dev.mailjet.com/getting-started/#api-in-a-nutshell) in the  *Getting Started* guide.


Cheers.
Gaëtan

**Comment by ODGithub** [comment]
Ok i think i understand a bit.
1) In the ApiKeyTotals there is no View part, and the documentation is wrong by stating that in the View tab:  
     # access the apikeytotals resource identified by $ID
     curl -s -X GET \    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
     https://api.mailjet.com/v3/REST/apikeytotals/$ID                  

2) Regarding the CampaignStatistics the same issue exists, even more obvious as to what i cannot perceive. It states in the View part that:

    # access the campaignstatistics resource identified by $ID
    curl -s -X GET \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \             
    https://api.mailjet.com/v3/REST/campaignstatistics/$ID
       
    # access the resource through the CustomValue's value
    # note: all keys marked as 'unique' may be used as an alternate ID
    curl -s -X GET \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
    https://api.mailjet.com/v3/REST/campaignstatistics/$CustomValue

Where are those stats? Should i consider something specific as they are Campaign stats? 

Thank you in advance 
OD

**Comment by GuillaumeBadi** [comment]
Hey! :airplane: 

We released a new version for this wrapper. It's a lighter/simpler version of the old one. Check it out:
https://github.com/mailjet/mailjet-apiv3-java/tree/v3.0.0
