### ISSUE TITLE
MailjetSocketTimeoutException sending email from android app 

### ISSUE THREAD

**Issue by digsub** [mailjet/mailjet-apiv3-java#130]
CODE:

```// Official Mailjet Java Wrapper https://github.com/mailjet/mailjet-apiv3-java#official-mailjet-java-wrapper

class MailJet {

    static void sendEmail(String recipient) {

        final String MJ_APIKEY_PUBLIC = redacted;
        final String MJ_APIKEY_PRIVATE = redacted;
        final String SENDER_EMAIL = redacted;

        MailjetClient client;
        MailjetRequest request;
        MailjetResponse response;

        try {
            client = new MailjetClient(MJ_APIKEY_PUBLIC, MJ_APIKEY_PRIVATE, new ClientOptions("v3.1"));
            request = new MailjetRequest(Emailv31.resource)
                    .property(Emailv31.MESSAGES, new JSONArray()
                            .put(new JSONObject()
                                    .put(Emailv31.Message.FROM, new JSONObject()
                                            .put("Email", SENDER_EMAIL)
                                            .put("Name", "Me"))
                                    .put(Emailv31.Message.TO, new JSONArray()
                                            .put(new JSONObject()
                                                    .put("Email", recipient)
                                                    .put("Name", "You")))
                                    .put(Emailv31.Message.SUBJECT, "My first Mailjet Email!")
                                    .put(Emailv31.Message.TEXTPART, "Greetings from Mailjet!")
                                    .put(Emailv31.Message.HTMLPART, "<h3>Dear passenger 1, welcome to <a href=\"https://www.mailjet.com/\">Mailjet</a>!</h3><br />May the delivery force be with you!")));
            client.setDebug(MailjetClient.VERBOSE_DEBUG);
            response = client.post(request);
            System.out.println(response.getStatus());
            System.out.println(response.getData());
        } catch(MailjetException mjException) {
            Log.e("XXXX", mjException.toString());
        } catch(MailjetSocketTimeoutException mjSocketTimeoutException) {
            Log.e("XXXX", mjSocketTimeoutException.toString());
        } catch(JSONException jsonException) {
            Log.e("XXXX", jsonException.toString());
        }
    }
}

```

INVOCATION:

```MailJet.sendEmail("recipient@somedomain.com");```

LOG:

> 2020-05-28 08:24:53.329 7572-7572/com.redacted.redacted I/System.out: POST https://api.mailjet.com/v3.1/send
2020-05-28 08:24:53.331 7572-7572/com.redacted.redacted I/System.out: user-agent:mailjet-apiv3-java/v4.5.0
2020-05-28 08:24:53.340 7572-7572/com.redacted.redacted W/System.err:     at com.mailjet.client.MailjetClient.post(MailjetClient.java:281)
2020-05-28 08:24:53.340 7572-7572/com.redacted.redacted W/System.err:     at com.redacted.redacted.MailJet.sendEmail(MailJet.java:45)
2020-05-28 08:24:53.343 7572-7572/com.redacted.redacted W/System.err:     at com.mailjet.client.MailjetClient.post(MailjetClient.java:281)
2020-05-28 08:24:53.343 7572-7572/com.redacted.redacted W/System.err:     at com.redacted.redacted.MailJet.sendEmail(MailJet.java:45)
2020-05-28 08:24:53.348 7572-7572/com.redacted.redacted E/XXXX: com.mailjet.client.errors.MailjetSocketTimeoutException: Socket Timeout

**Comment by digsub** [comment]
This issue seems similar to #129 so I tried the following without success:


    implementation 'com.mailjet:mailjet-client:4.2.1'

or

    implementation 'com.mailjet:mailjet-client:4.5.0'

    with this added to above code...


        try {
            myClientOptions = new ClientOptions("v3.1");
            myClientOptions.setTimeout(8000);
            client = new MailjetClient(MJ_APIKEY_PUBLIC, MJ_APIKEY_PRIVATE, myClientOptions);

**Comment by goacoustic** [comment]
@digsub Hi!

I checked the given code block and seems like it works. 
Could you please provide more details and try the same code from a regular java console instead of android?

**Comment by goacoustic** [comment]
@digsub HI, going to close this as a bit outdated. If the issue still occurs - please, comment here or open the new issue.
