### ISSUE TITLE
SocketTimeoutException instead of MailjetSocketTimeoutException

### ISSUE THREAD

**Issue by maksym-shamanovskyi-axon** [mailjet/mailjet-apiv3-java#133]
It's a first time when we got this 
`com.turbomanage.httpclient.HttpRequestException: java.net.SocketTimeoutException: connect timed out
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:236)
	at com.turbomanage.httpclient.AbstractHttpClient.execute(AbstractHttpClient.java:173)
	at com.turbomanage.httpclient.AbstractHttpClient.post(AbstractHttpClient.java:130)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:280)`

I think we should get MailjetSocketTimeoutException instead of this.

**Comment by maksym-shamanovskyi-axon** [comment]
Any updates?

**Comment by goacoustic** [comment]
@maksym-shamanovskyi-axon Hi!
It seems legit to rethrow MailjetSocketTimeoutException instead of SocketTimeoutException, especially when we already have such type in the package defined. Will look into this deeper.

**Comment by goacoustic** [comment]
Hi @maksym-shamanovskyi-axon,

I checked in more detail, and it seems like not so straight-forward.

Right now we throw `MailjetSocketTimeoutException` in case receiving a null response from the HTTP client layer, which is no quite accurate as for me, as this not exactly means something wrong with the socket.

The exception that you mentioned going also from the HTTP client layer, and of course, we could catch '
SocketTimeoutException' or even all `IOException` from the java.net and rethrow `MailjetSocketTimeoutException`, but I see not much sense in it - we just mask origin exception, losing information without any benefits.

I'd rather mark MailJet client methods as `throws IOException` to indicate such behavior explicitly and remove `MailjetSocketTimeoutException` at all. To indicate unsuccessful communication with the MailJet server, another exception could be introduced, like [MailjetClientException](https://github.com/mailjet/mailjet-apiv3-java/blob/01314d74aba85ba1457ecc98ea6953fcd3a30ae9/src/main/java/com/mailjet/client/errors/MailjetClientException.java).

@maksym-shamanovskyi-axon do you have any thoughts/objections?

**Comment by maksym-shamanovskyi-axon** [comment]
Hello @goacoustic, I like your solution, anyway it will be more transparent and useful than the current implementation.

**Comment by goacoustic** [comment]
@maksym-shamanovskyi-axon 
I overthink implementation a bit and it seems more logical to have IOException wrapped.
Now all possible exceptions from inside the mailjet client are wrapped in `MailjetException`
