### ISSUE TITLE
Can you please cut a release?

### ISSUE THREAD

**Issue by rethab** [mailjet/mailjet-apiv3-java#139]
Apologies if this is the wrong way to request something like this, but it would be really cool if you could cut a release, because the current version brings (and old version of) junit on the classpath which has a vulnerability (see https://github.com/junit-team/junit4/security/advisories/GHSA-269g-pwp5-87pp). I see the test scope is already fixed on `master` though (https://github.com/jmfsilva/mailjet-apiv3-java/commit/fc014d40d565364de0a1a4e1208640b7f6857158).

If there's any work needed to make this happen, please let me know -- I'd be happy to help.

Thanks :)

_/edit: Note to self: If `master` is realeased as is, there is a breaking change. Previously, any "Bad Requests" lead to an exception, but now only those that respond with invalid json. This means if someone relies on exceptions being thrown, that is no longer valid: https://github.com/mailjet/mailjet-apiv3-java/commit/f5498130b35d1d72a8be5b7b06f578a6bd96835f_

**Comment by goacoustic** [comment]
@rethab Hi, just interested - have you relied/used exactly this exception anyhow?

**Comment by rethab** [comment]
> @rethab Hi, just interested - have you relied/used exactly this exception anyhow?

My code currently looks something like this:

```java
try {
  extractResponse(mailjetClient.post(request))
} catch (ex: MailjetException) {
  // something went wrong
}
```
in other words, I expect that if no exception is thrown, everything is good and I can continue processing the response as a success. With the linked change, as far as I understand, I'd need an additional `if (reponse.code == 200)` (or similar) to make sure the processing only happens if it is actually successful.

**Comment by goacoustic** [comment]
@rethab Your point is valid, thanks
Implementation has been changed to not have breaking changes - in the latest version all methods except bulk will throw an instance of `MailjetException` in case of unsuccess response.
