### ISSUE TITLE
Improve binary compatibility of okhttp

### ISSUE THREAD

**Issue by rethab** [mailjet/mailjet-apiv3-java#144]
Hi, I see you have moved to okhttp with the latest version. Would you mind using the latest `3.X` of that library or are you using something specific from version 4?

The problem is that major frameworks such as spring boot still come with okhttp 3 (see https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-dependency-versions.html) and you're using a method that was not there in okhttp version 3 (see stacktrace below).

Using version 3 as your dependency should be not problem if other projects already come with version 4 on their classpath, because they say it is backwards compatible (see https://square.github.io/okhttp/upgrading_to_okhttp_4/).

Alternatively, flipping the parameters passed to the method `create` might also fix this specific issue, but I think using version would also prevent against the same issue in the future.

If you agree that this is a good idea, but don't have the time to change it, I'd be happy to draft a PR.

Thanks :) 

----
Stacktrace:
```
java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(byte[], okhttp3.MediaType)'
        at com.mailjet.client.MailjetClient.post(MailjetClient.java:110)
```

**Comment by goacoustic** [comment]
Hi @rethab, thanks for raising the issue.

I see some points in using the same version as spring boot uses.
Still hesitate thou about using v3, as v4 has an active development stream and this is the future of okhttp. 

But for now, I think it should be ok, if there are not many efforts to downgrade.

**Comment by goacoustic** [comment]
@rethab thanks for the code review!
new version 5.1.0 contains with your changes has been published.
