### ISSUE TITLE
Error when using TransactionalEmail and SendEmailsRequest

### ISSUE THREAD

**Issue by cristiammercado** [mailjet/mailjet-apiv3-java#147]
Hi,

I have just migrated the `mailjet-client` library to version `5.1.0` in my project. I use only the transactional emails part and I have my templates previously created on the Mailjet web platform. I implemented a refactoring in my code with the `TransactionalEmail` class, which allows to have the code much more readable than the implementation with `JSONObject` and `MailjetRequest`. This is a part of the code:

Client creation:

```
OkHttpClient okHttpClient = new OkHttpClient.Builder()
    .connectTimeout(config.getTimeout(), TimeUnit.MILLISECONDS)
    .readTimeout(config.getTimeout(), TimeUnit.MILLISECONDS)
    .writeTimeout(config.getTimeout(), TimeUnit.MILLISECONDS)
    .build();

ClientOptions options = ClientOptions.builder()
    .apiKey(config.getKey())
    .apiSecretKey(config.getSecret())
    .okHttpClient(okHttpClient)
    .build();

MailjetClient client = new MailjetClient(options);
```

Client usage:

```
JSONObject variables = new JSONObject(email.variables());

TransactionalEmail message = TransactionalEmail
    .builder()
    .to(new SendContact(email.toEmail(), email.toName()))
    .from(new SendContact(email.fromEmail(), email.fromName()))
    .templateID(email.templateId())
    .templateLanguage(true)
    .priority(email.priority())
    .customID(email.id())
    .variables(variables.toMap())
    .trackOpens(TrackOpens.ENABLED)
    .trackClicks(TrackClicks.ENABLED)
    .build();
    
SendEmailsRequest request = SendEmailsRequest.builder()
    .AdvanceErrorHandling(true)
    .message(message)
    .build();
    
SendEmailsResponse response = request.sendWith(client);
```

The problem is when the `SendEmailsRequest.sendWith` method is invoked, it does not send the mail, but is generating this error from the API:

`SendEmailsResponse (messages = [MessageResult (status = ERROR, errors = [SendEmailError (errorIdentifier = xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx, errorCode = send-0019, statusCode = 400, errorMessage string = Wrong type for template header, expected type "string", errorRelatedTo = [sender])], customID = null, to = null, cc = null, bcc = null)])`

I've been debugging step by step but I've not been able to find the error, it seems the JSON that it sends in the `OkHTTPClient` request is correct, maybe you can help me.

Thanks in advance!

**Comment by cristiammercado** [comment]
UPDATE:

After a more precise comparison between the body generated by `MailjetRequest` vs the one generated by `SendEmailsRequest` and making direct calls to the API with the two bodies, the conclusion is that `SendEmailsRequest` adds two variables at the same level of `Messages`: `AdvanceErrorHandling` and `SandboxMode`. By removing them from the body in the REST invocation the API sends the transactional email without problem.

In conclusion, through the new `SendEmailsRequest` class it's not possible to eliminate these two parameters (`AdvanceErrorHandling` and `SandboxMode`) and they're always sent in the body even if they are not configured, which causes the API invocation to fail.

Body with error:

```
{
  "AdvanceErrorHandling": true,
  "Messages": [
    {
      "Cc": [],
      "Bcc": [],
      "Priority": 3,
      "Headers": {},
      "From": {
        "Email": "xxxxx@xxxxxxxxxxx.com",
        "Name": "xxxxxxxxx"
      },
      "Attachments": [],
      "TemplateLanguage": true,
      "TrackOpens": "enabled",
      "Variables": {
        "A_VARIABLE": "A variable body"
      },
      "CustomID": "c2712fb1-e607-485c-b7fc-xxxxxxxxxxxx",
      "InlinedAttachments": [],
      "To": [
        {
          "Email": "xxxxxxxxx@xxxxxxxxx.com",
          "Name": "xxxxxxxxxxx"
        }
      ],
      "TemplateID": 1234567
    }
  ],
  "SandboxMode": false
}
```

Body success:

```
{
  "Messages": [
    {
      "Cc": [],
      "Bcc": [],
      "Priority": 3,
      "Headers": {},
      "From": {
        "Email": "xxxxx@xxxxxxxxxxx.com",
        "Name": "xxxxxxxxx"
      },
      "Attachments": [],
      "TemplateLanguage": true,
      "TrackOpens": "enabled",
      "Variables": {
        "A_VARIABLE": "A variable body"
      },
      "CustomID": "c2712fb1-e607-485c-b7fc-xxxxxxxxxxxx",
      "InlinedAttachments": [],
      "To": [
        {
          "Email": "xxxxxxxxx@xxxxxxxxx.com",
          "Name": "xxxxxxxxxxx"
        }
      ],
      "TemplateID": 1234567
    }
  ]
}
```

**Comment by goacoustic** [comment]
@cristiammercado Hi! 
Thanks for raising this issue and providing an excessive investigation, this is really helpful!

Seems like having a message without the sender generates a warning on the API side, that escalates into an error with `AdvanceErrorHandling`
just a stupid question - have you tried 

``` java
SendEmailsRequest request = SendEmailsRequest.builder()
    .AdvanceErrorHandling(false)
...
```

?

**Comment by goacoustic** [comment]
btw anyway I see some inconsistency in naming, and default behavior with this variable, so I propose to adjust it a bit.

**Comment by cristiammercado** [comment]
Hi @goacoustic,

Your suggestion:

> just a stupid question - have you tried
>
>SendEmailsRequest request = SendEmailsRequest.builder()
>    .AdvanceErrorHandling(false)
> ...

worked! It was as simple as changing the parameter to `false`!

Unfortunately in the documentation the description of that value (`AdvanceErrorHandling`) doesn't appear, so I didn't really know what function that parameter had.

![image](https://user-images.githubusercontent.com/4806666/102564500-934ed580-40a9-11eb-8490-f67bc6b6b310.png)

I can already use `TransactionalEmail` correctly. Although in a simple implementation it should not be set to `false` to work properly. I think that's the MR you just opened is about.

Thanks you so mucho for the tip, not at all stupid! Hahahahahaa

**Comment by goacoustic** [comment]
@cristiammercado just in case - there is [API reference](https://dev.mailjet.com/email/reference/send-emails/#v3_1_post_send) section on the site, sometimes it has more information than step-by-step guides.

So, I'm gonna merge defaulting behavior to false, it will be accessible in the new version of the package.
