### ISSUE TITLE
Nested variables

### ISSUE THREAD

**Issue by Belsepubi** [mailjet/mailjet-apiv3-java#154]
Hi,

Faced issues with 50 max message per request and same time updated to newest release from 4.5.0. However I cannot set variables right with new syntax. I have nested variables in transactional templates. E.g. task -> items. With "old" syntax meaning JSONObject can contain other JSONObject that may contain List of JSONObjects. I couldn´t find an example anywhere.

**Comment by goacoustic** [comment]
Hi @Belsepubi,

There is an example with complex variables [here](https://github.com/mailjet/mailjet-apiv3-java/blob/ae1441bc471dbd182bca71b102184ba2544edb78/src/test/java/com/mailjet/client/TransactionalEmailBuilderTest.java#L55)

Basically, variables are represented as Map<String, Object>, where Object value can be the collection of collections... with any level of nesting depth.

Will it work for you?

**Comment by goacoustic** [comment]
Closing ticket due to inactivity
If there are any questions still, please, reopen
