### ISSUE TITLE
Add Automatic-Module-Name in the manifest

### ISSUE THREAD

**Issue by jkuhn1** [mailjet/mailjet-apiv3-java#158]
Hello,

The project is currently packaged and distributed as an unnamed Java module (no module-info.java, no Automatic-Module-Name property set in the manifest) which makes it difficult to use in a modular Java application: the module is basically deduced from the Jar file name which is clearly not ideal.

Could you please set a module name in the manifest when packaging the artifact, eg:

`Automatic-Module-Name: mailjet.apiv3`

An even better solution would be to properly modularize the project but providing previous property should be enough.

Thanks

**Comment by goacoustic** [comment]
@jkuhn1 hi, thanks for raising this issue!
added in v5.2.0. 
if you have any feedback, please, open a new issue
