### ISSUE TITLE
Asynchronous API

### ISSUE THREAD

**Issue by denisw** [mailjet/mailjet-apiv3-java#159]
Hi,

Our team evaluated the use for this Java SDK for interacting with MailJet from a Spring Boot WebFlux application. What is blocking us from using it is that all calls seem to be blocking and synchronous. Would it be possible to also offer non-blocking versions of the SDK's API call methods, perhaps by returning a [CompletableFuture](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletableFuture.html)?

**Comment by goacoustic** [comment]
@denisw hi, thanks for raising this issue!
async methods are added in v5.2.0. 
if you have any feedback, please, open a new issue

**Comment by denisw** [comment]
@goacoustic Thank you for fixing and releasing this so quickly! That will be great help to us - now we don’t need to manually call the REST API anymore. 😃
