### ISSUE TITLE
ManyContacts 

### ISSUE THREAD

**Issue by ODGithub** [mailjet/mailjet-apiv3-java#16]
Hi
i cannot find the manycontacts class to call it, and also i cannot find the according Action class as well. 
Do they exist? 
If yes, can you please write specific name to call?

Kind regards
OD

**Comment by GuillaumeBadi** [comment]
Hello @ODGithub ,

Thank you for using the Mailjet API.

The Action class is not supported yet, it is however under active development. You should be able to use it soon.

Regards,
Guillaume.
