### ISSUE TITLE
MessageHistory, no GET working

### ISSUE THREAD

**Issue by ODGithub** [mailjet/mailjet-apiv3-java#17]
In messagehistory class, no GET seems to be working.

Firstly, when i try to call your url 
https://api.mailjet.com/v3/REST/messagehistory
with my credentials i get
    { "ErrorIdentifier" : "24C9B990-C8C6-4E19-976E-E4B62A512076", "ErrorInfo" : "", "ErrorMessage" :     "Unexpected database error during GET", "StatusCode" : 500 }

Secondly, .List is an option, even though it does not work by my implementation, but there is no way to use the View function, as there is no .Get nor an ID to search by.

    # access the messagehistory resource identified by $ID
    curl -s -X GET \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
    https://api.mailjet.com/v3/REST/messagehistory/$ID

**Comment by michalgce** [comment]
+1
