### ISSUE TITLE
Release 5.2.1 not tagged and not published to maven

### ISSUE THREAD

**Issue by holophil** [mailjet/mailjet-apiv3-java#177]
The release 5.2.1 mentioned in the release notes https://github.com/mailjet/mailjet-apiv3-java#release-notes is not tagged and not available on maven.

Please publish the version 5.2.1 to maven to let us integrate the latest and greatest dependency upgrades.

Thank you.

**Comment by OmarHawk** [comment]
@szagr we need that as well...

**Comment by szagr** [comment]
I've been waiting a month for permission to publish this to maven.
As soon as I receive it, it will be published.
If you could speed up this process, that would be great.

**Comment by Just-Fun** [comment]
Or maybe someone with permissions can just publish to Maven Central.

**Comment by szagr** [comment]
Fixed

**Comment by holophil** [comment]
Thank you!
