### ISSUE TITLE
Metadata and MessageInformation Properties 

### ISSUE THREAD

**Issue by ODGithub** [mailjet/mailjet-apiv3-java#18]
I encountered the almost same issue in both of my implementations.

While i wrote and called both MetadataProperty and MessageInformationProperty,
the compiler of Eclipse broke, stating in the beginning at the declaration of the package the class belongs, these messages, accordingly to each class:

MetadataClass: The type com.mailjet.api.model.v3.customtypes.Property cannot be resolved. It is indirectly referenced from required .class files
MessageInformationClass: The type com.mailjet.api.model.v3.customtypes.SpamAssassinRuleList cannot be resolved. It is indirectly referenced from required .class 
 files

Thank you for your help in advance
OD

**Comment by michalgce** [comment]
+1
