### ISSUE TITLE
Csvimport.DATA does not exist

### ISSUE THREAD

**Issue by yolefebvre** [mailjet/mailjet-apiv3-java#183]
I want to use upload and I copy the code found in the doc for java.

But, there is no DATA in the Csvimport class.

Csvimport.**DATA**

[https://dev.mailjet.com/email/guides/contact-management/#manage-contacts-via-csv-upload](url)
package com.my.project;
import com.mailjet.client.errors.MailjetException;
import com.mailjet.client.errors.MailjetSocketTimeoutException;
import com.mailjet.client.MailjetClient;
import com.mailjet.client.MailjetRequest;
import com.mailjet.client.MailjetResponse;
import com.mailjet.client.resource.Csvimport;
import org.json.JSONArray;
import org.json.JSONObject;
public class MyClass {
    /**
     * Modify : A wrapper for the CSV importer
     */
    public static void main(String[] args) throws MailjetException, MailjetSocketTimeoutException {
      MailjetClient client;
      MailjetRequest request;
      MailjetResponse response;
      client = new MailjetClient(System.getenv("MJ_APIKEY_PUBLIC"), System.getenv("MJ_APIKEY_PRIVATE"));
      request = new MailjetRequest(Csvimport.resource, ID)
        .property(Csvimport.**DATA**, MYFILE);
      response = client.put(request);
      System.out.println(response.getStatus());
      System.out.println(response.getData());
    }
}

[https://github.com/mailjet/mailjet-apiv3-java/issues/62
![CSVImport](https://user-images.githubusercontent.com/113695453/220162366-83f2c649-e505-42cc-9182-78696ba1678a.jpg)
](url)

**Comment by vitalii-chornobryvyi-swi** [comment]
the issue has been fixed, commented on and is closed due to the lack of an answer
