### ISSUE TITLE
Message Result 'To' is null

### ISSUE THREAD

**Issue by LucasTavernier** [mailjet/mailjet-apiv3-java#191]
Hi, today i sent 100 mails and got this error :

```java
"Cannot invoke \"java.util.List.get(int)\" because the return value of \"com.mailjet.client.transactional.response.MessageResult.getTo()\" is null"
``` 

It's a weird behavior because all my mails have been sent, i get this information from the stats panel directly in jetmail.
Can someone help me on this please ?

**Comment by vitalii-chornobryvyi-swi** [comment]
@LucasTavernier  thanks for raising this issue!
Sorry for the late reply.
I can't reproduce this issue. Please let us know if everything works for you and do you still facing an issue?

**Comment by vitalii-chornobryvyi-swi** [comment]
the issue has been commented on and is closed due to the lack of an answer
