### ISSUE TITLE
Socket Exception

### ISSUE THREAD

**Issue by nseb** [mailjet/mailjet-apiv3-java#194]
Hi , 
follow this [issue](https://github.com/mailjet/mailjet-apiv3-java/issues/108)

@todorDim , Hello , why client keep connection open ?
The problem when you don't have a lot of email, the socket closes, without you knowing.
Isn't there a method to verify that the client is up before calling without meeting each time?

**Comment by vitalii-chornobryvyi-swi** [comment]
HI @nseb, thanks for raising this issue!
Sorry for the late reply.
Did you have a chance to try the [solution](https://github.com/mailjet/mailjet-apiv3-java/issues/108#issuecomment-462789921) mentioned by the author of the initial [issue](https://github.com/mailjet/mailjet-apiv3-java/issues/108) that you referenced? Based on the author's comment everything works fine

**Comment by vitalii-chornobryvyi-swi** [comment]
the issue has been commented on and is closed due to the lack of an answer
