### ISSUE TITLE
Add possibility to use DATA API

### ISSUE THREAD

**Issue by Jul13nT** [mailjet/mailjet-apiv3-java#2]
Hi,

It seems that this wrapper only allow to use the REST API. Can you provide an update to allow also to use the DATA API ? You can have an sample of utilisation at this URL : http://dev.mailjet.com/guides/newsletter-guide/  "Adding an HTML body to a newsletter".
It would be great to upload CSV and HTML files from this wrapper to use them in the REST API.

Thanks,
Julien

**Comment by Jul13nT** [comment]
Up.

**Comment by GuillaumeBadi** [comment]
News ! :airplane: 

We released a new version for this wrapper. It's a lighter/simpler version of the old one. Check it out:
https://github.com/mailjet/mailjet-apiv3-java/tree/v3.0.0
