### ISSUE TITLE
Exception when building client

### ISSUE THREAD

**Issue by alexvndre** [mailjet/mailjet-apiv3-java#36]
Hi,

I am starting to use your library to send emails. But when I am building the client, I am encountering this exception:
`java.lang.reflect.InvocationTargetException
com.mailjet.api.client.config.MailJetClientConfigurationException: java.lang.reflect.InvocationTargetException`

I am using the code in example:
```
MailJetClientConfiguration config = new MailJetClientConfiguration()
		        .setBaseUrl("https://api.mailjet.com/v3/")            
		        .setDefaultApiKey(Email.apiKey)
		        .setDefaultSecretKey(Email.secretKey);
		
MailJetApiClient client = config.buildClient();
```

Any idea? Thanks!

**Comment by GuillaumeBadi** [comment]
Hey :airplane: !

We released a new tag for this wrapper !
So your code would be:

``` java
MailjetClient client = new MailjetClient("apikey", "apisecret");
```
