### ISSUE TITLE
Get MailJet ID

### ISSUE THREAD

**Issue by plaeplia** [mailjet/mailjet-apiv3-java#37]
I know that I can generate and use a CustomID, but I would like to also save an ID that I become from MailJet after Send API request:

Request:
curl -X POST --user "xxx:yyy" https://api.mailjet.com/v3/send/message
 -F from='Mr Mailjet <fromEmail@email.com>'
 -F to=toEmail@email.com
 -F subject='Hello World!'
 -F text='Greetings from Mailjet.'

Response:
```json
{
 "Count" : 1,
 "Data" : [
  { "ID" : 199999999999 }
 ],
 "Total" : 1
}
```
Is it possible to become this ID with Mailjet Java API Wrapper?

**Comment by arnaudbreton** [comment]
Hi @plaeplia, 

Thanks for your interest in Mailjet API. Please visit our [API Guide about CustomID](http://dev.mailjet.com/guides/?go#tagging-email-messages).

Hope it helps,
Arnaud.
