### ISSUE TITLE
trying new wrapper

### ISSUE THREAD

**Issue by ODGithub** [mailjet/mailjet-apiv3-java#43]
sorry i just checked new api structure. i am sorry

**Comment by GuillaumeBadi** [comment]
Hey @ODGithub !

We truly apologize for the inconvenience.

A few weeks ago, we decided to put the first version of our Java API v3 Wrapper in a maintenance mode (limiting to only bug and security fixes) and release a new version, semantic with our API itself, easier to onboard and integrate in your system, while obviously remaining idiomatic with Java itself.

Using our new wrapper, most of your open issues with the now deprecated version could be considered as solved. Again, we apologize for these issues you’ve experienced and hope that the new version will satisfy you better! 

As always, I’m here to help you transition to the new wrapper and help you integrate with our API.

Best,
Guillaume
