### ISSUE TITLE
Campaigns

### ISSUE THREAD

**Issue by sicoa** [mailjet/mailjet-apiv3-java#45]
Greetings again
2 issues:

1)
I have a problem retrieving my campaigns.
I use the same code to retrieve successfully lets say Contacts, and when i try requesting Campaign.resource, i get empty result, even though i have created many. Could you please check if the functionality is as expected?
2)
In addition, all stats, as i have seen from for the filters' implementation have been changed. All of them are Strings i suppose. For example, what used to be Long like CampaignID or Date like FromTS or even Boolean attributes, have all been reviewed to Strings at the new API. Also the documentation has remained the same as before the update, stating the previous attributes' types.
Is this intentionally made so or does it need fixing?

Thank you in advance for your reply
Remaining yours
SicoaDev

**Comment by GuillaumeBadi** [comment]
Hey @sicoa !

1) Could you provide your code and a console output with debug mode on like so ?
``` java
        client.setDebug(MailjetClient.VERBOSE_DEBUG);
        
        MailjetRequest request = new MailjetRequest(Campaign.resource)
                    // .filter(..., ...)
                    ;
        
        MailjetResponse campaign = client.get(request);
        
```

my output is : 
``` java
=== HTTP Request ===
GET https://api.mailjet.com/v3/REST/campaign?
Accept-Charset:UTF-8
user-agent:mailjet-apiv3-java/v3.0.0
Accept:application/json
=== HTTP Response ===
Receive url: https://api.mailjet.com/v3/REST/campaign?
Status: 200
null:HTTP/1.1 200 OK
Date:Thu, 03 Dec 2015 10:52:25 GMT
Content-Length:41
Connection:keep-alive
Content-Type:application/json
Server:nginx
```

2)  At the moment, [`filter` accepts both `String` and `int`](https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/MailjetRequest.java#L214) . Do you think we should add `Long` and `Dates` back ?

when you say: "Also the documentation has remained the same as before the update, stating the previous attributes' types", are you talking about the `README.md` ?

Best,
Guillaume from Mailjet!

**Comment by sicoa** [comment]
Thank you once more for the quick reply Mr Guillaume!

2) When i said documentation, i meant the v3 reference
Regarding filters, as long as it works, i would not change them, I do like more the Int/String only values (i will try the date implementation, as date is a strange format)
1)
My account for testing, the one i use the creds from, has 6 campaigns made.
The response i get is the same as yours but i do not get any Data: 
{"Status":200,"Total":0,"Data":[],"Count":0}

Output in the console:
=== HTTP Request ===
GET https://api.mailjet.com/v3/REST/campaign?FromID=0&ContactsList=0
Accept-Charset:UTF-8
Accept:application/json
user-agent:mailjet-apiv3-java/v3.0.0
=== HTTP Response ===
Receive url: https://api.mailjet.com/v3/REST/campaign?FromID=0&ContactsList=0
Status: 200
null:HTTP/1.1 200 OK
Server:nginx
Connection:keep-alive
Content-Length:41
Date:Thu, 03 Dec 2015 11:15:48 GMT
Content-Type:application/json
Content:
{ "Count" : 0, "Data" : [], "Total" : 0 }

**Comment by sicoa** [comment]
Regarding filters, what has happened to the Boolean ones? They recognize only true/false String values?

**Comment by GuillaumeBadi** [comment]
I assume this is your call then (?)

``` java
        
    new MailjetRequest(Campaign.resource)
                    .filter(Campaign.FROMID, 0)
                    .filter(Campaign.CAMPAIGNID, 0);
```

Can you make sure you've got a sender with ID 0 and a Contact list with id 0 ?

Regarding Boolean in filters, yeah, I am definitly adding them, you are right

**Comment by sicoa** [comment]
Well, i do not use any filter as my response suggests. A plain Campaign.resource call.
This is definitely an inside bug.

FILTERS:
Please can you specify to me if the v3 reference is actual? I mean the filters for example. 
When i call "Contact." like "request.filter(Contact.CONTACTSLIST,contlistfilter);" i have the option of filtering with many more attributes than the ones listed at the v3REFERENCE. Does it work? Do i have all those filters that are Contact stats AND filters from the old ones? Example: Contact.CAMPAIGN exists and in the previous version, meant only filter, as it is not a Contact attribute. Now it is there along with the rest of the filters AND the attributes for Contact

**Comment by GuillaumeBadi** [comment]
The v3 reference is up to date. The Resource propreties are actually helper for autocompletion. So they are valid for filters AND body (for POST/PUT) fields. They are just [strings](https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/resource/Campaign.java#L18) actually.

I tried to reproduce your error, but I can't, it is weird. This code produces this output for me:
``` java
        client.setDebug(MailjetClient.VERBOSE_DEBUG);

        MailjetRequest request;
        MailjetResponse response;

        request = new MailjetRequest(Campaign.resource);
        response = client.get(request);
```

``` java
=== HTTP Request ===
GET https://api.mailjet.com/v3/REST/campaign?
Accept-Charset:UTF-8
Accept:application/json
user-agent:mailjet-apiv3-java/v3.0.0
=== HTTP Response ===
Receive url: https://api.mailjet.com/v3/REST/campaign?
Status: 200
null:HTTP/1.1 200 OK
Server:nginx
Connection:keep-alive
Content-Length:41
Date:Thu, 03 Dec 2015 13:13:53 GMT
Content-Type:application/json
```
the interesting line is `GET https://api.mailjet.com/v3/REST/campaign?`
Yours is `GET https://api.mailjet.com/v3/REST/campaign?FromID=0&ContactsList=0`

It is hard to tell where the bug comes from in the wrapper then..

**Comment by sicoa** [comment]
Mr Guillaume 
i am truly sorry for the frustration, i seem to have forgotten initial values at the previous implementation for those two specific stats that used to be non strings (long or int i believe)
Thank you a lot for your effort to solve the issue!
However i still cannot get the content from the campaigns:

=== HTTP Request ===
GET https://api.mailjet.com/v3/REST/campaign?
Accept-Charset:UTF-8
Accept:application/json
user-agent:mailjet-apiv3-java/v3.0.0
=== HTTP Response ===
Receive url: https://api.mailjet.com/v3/REST/campaign?
Status: 200
null:HTTP/1.1 200 OK
Server:nginx
Connection:keep-alive
Content-Length:41
Date:Thu, 03 Dec 2015 14:01:23 GMT
Content-Type:application/json
Content:
{ "Count" : 0, "Data" : [], "Total" : 0 }

**Comment by GuillaumeBadi** [comment]
Don't worry ;)

So the http call is working normally, now it might be related to the server. What do you get when you type in your terminal:

``` bash
curl -X GET --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" http://api.mailjet.com/v3/REST/Campaign
```
with the correct API credentials ?

**Comment by sicoa** [comment]
Calling the url you gave me with the correct credentials, it returns exactly the same response:
{ "Count" : 0, "Data" : [], "Total" : 0 }
However i do have 6 campaigns under the CAMPAIGN tab..
What am i supposed to be looking at as a response?

One comment regarding v3reference. Apart from the change in the types of variables as we discussed before concerning Dates etc, for example i just stumbled upon 
Contact Filter: Recipient 	Only retrieve contacts corresponding to this recipient. [ Type Int64 ] This does not exist in the Contact properties..

**Comment by GuillaumeBadi** [comment]
Ow, my bad, I get it now!
The request made without the FromTS filter will return all the Campaigns made today only.

Try this for all campagins from day 0:
``` java 
        MailjetRequest request;
        MailjetResponse response;

        request = new MailjetRequest(Campaign.resource)
                    .filter(Campaign.FROMTS, 1);
        response = client.get(request);
        System.out.println(response);
```

Again, sorry for the inconvenience!

Best,
Guillaume

**Comment by GuillaumeBadi** [comment]
Does it work on your side ?

**Comment by sicoa** [comment]
It worked like charm Mr Guillaume!
Thank you for all your help and immediate responses
Best regards
SicoaDev

ps. Did you check my comment on Contact Filter: Recipient ? Shall i open a new issue maybe for any gaps/controversially documented parts etc that i may find?
