### ISSUE TITLE
ListRecipient issues

### ISSUE THREAD

**Issue by sicoa** [mailjet/mailjet-apiv3-java#47]
Greetings once more
and straight to the point :)
ListRecipient has a number of issues for me:
1)
When listed, the contents have an attribute, not shown in the documentation: “ListName”. Is this supposed to be available at update and create?

2)
Cannot create a ListRecipient:
When trying to Create a new ListRecipient  setting the mandatory ContactListID
the call is below and i provide values for all but UnsubscribedAt
``` java
request = new MailjetRequest(Listrecipient.resource)
					            .property(Listrecipient.ACTIVE, IsActive)
					            .property(Listrecipient.ISUNSUBSCRIBED, IsUnsubscribed)
					            .property(Listrecipient.UNSUBSCRIBEDAT, UnsubscribedAt)
					            .property(Listrecipient.CONTACTSLIST, ContactListID);
```
In the end of the call the request is:
```
{"Filters":"{}","Body":"{\"ContactsList\":1,\"Active\":true,\"IsUnsubscribed\":false,\"UnsubscribedAt\":\"\"}","Resource":"listrecipient","ID":0,"Action ID":0}
```

And finally, the response:
```
{"ErrorInfo":"","StatusCode":400,"Status":400,"ErrorMessage":"Invalid json input: object \"\"->\"TListRecipient\" has no property \"ContactsList\""}
```

3)
Cannot update a ListRecipient
When i tried to update IsActive from false to true, and only that, i got:
WITH PUT (`update = new MailjetRequest(Listrecipient.resource, listRecipient.getLong("ID")).setBody(listRecipient.put(Listrecipient.ISACTIVE, isActive));`)
->
```
{"ErrorInfo":"","StatusCode":400,"Status":400,"ErrorMessage":"Invalid json input: object \"\"->\"TListRecipient\" has no property \"ListName\""}
```

Once more at client.put(update)
update is correct but the response is the above
update:
```
{"Filters":"{}","Body":"{\"IsUnsubscribed\":false,\"UnsubscribedAt\":\"\",\"IsActive\":true,\"ID\":34,\"ContactID\":2,\"ListID\":1,\"ListName\”:\”test\”}”,”Resource":"listrecipient","Action":"","ID":34,"Action ID":0}
```

WITHOUT PUT (update = new MailjetRequest(Listrecipient.resource, listRecipient.getLong("ID”).property(Listrecipient.ISACTIVE, isActive);)
->
update:
{"Filters":"{}","Body":"{\"IsActive\":true}","Resource":"listrecipient","Action":"","ID":34,"Action ID":0}
and i get the following exception when cl.put(update) is called
exception [org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]] with root cause
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

4)
Delete seems to be broken as well, if i get this right.
I call: 
request = new MailjetRequest(Listrecipient.resource, id);
response=cl.delete(request);

This returns the Listrecipient and does not delete it.

**Comment by GuillaumeBadi** [comment]
Hey ! :airplane: 

I indeed need to implement a distinction between Filters and properties in the wrapper. You cannot `POST/PUT` with filters. You can see the props/filters here at the moment: http://dev.mailjet.com/email-api/v3/listrecipient/

Could you try to see the `PUT` results with cUrl ? I think when you make a `PUT` without changing anything, it sends a non-json 304 response, and the Wrapper does not support non-json response yet. Its actually a bug

**Comment by sicoa** [comment]
Hi there sir
thank you once more for the reply

1) Attribute issue
2) Create issue
3) Update issue
4) Delete issue
I did not use filters.

**Comment by GuillaumeBadi** [comment]
Hey ther!
`Contactslist` is not a valid property: http://dev.mailjet.com/email-api/v3/listrecipient/

You can simply create a list via different endpoints:
```
http://dev.mailjet.com/email-api/v3/contact-managecontactslists/
http://dev.mailjet.com/email-api/v3/contact-managemanycontacts/
http://dev.mailjet.com/email-api/v3/contactslist-managecontact/
http://dev.mailjet.com/email-api/v3/contactslist-managemanycontacts/
```
Listrecipient is not a stable way of doing the job. We didn't even featured it in the API guide

The update is I guess a 304 error that don't send any JSON back (I need to fix that): it means that the content has not been changed because the payload was not changing anything. Can you make sure with debug logging ?

**Comment by sicoa** [comment]
Greetings
some comments:
I did not understand your last reply to be honest. I was talking about Listrecipients, not ContactsList. 
Although for some reason when trying to list the Listrecipients, the request shows a JSON with Contactslist for resource (issue in here no2).

Secondly, i did not understand why Listrecipientis not valid. http://dev.mailjet.com/email-api/v3/listrecipient/   : it is very clearly stated what it does. If it does not work then maybe the Reference is wrong.

Finally, in general is "delete" stated correctly as shown above?

Thank you in advance for your reply

**Comment by GuillaumeBadi** [comment]
Hey @sicoa ! Sorry for the delay! :)

I have created a new branch `@sicoa-fixes` that contains a fix for the `delete` that now works and a fix for the JSONExceptions. The `delete` was actually performing a `get`..

So inside that branch this works for me:
``` java
public class Main {
    public static void main(String[] args) throws MailjetException {
        MailjetClient client = new MailjetClient("", "");
        client.setDebug(MailjetClient.VERBOSE_DEBUG);

        System.out.println("POST REQUEST");
        MailjetRequest postRequest = new MailjetRequest(Listrecipient.resource)
                                .property(Listrecipient.ISACTIVE, true)
                                .property(Listrecipient.ISUNSUBSCRIBED, false)
                                .property(Listrecipient.LISTID, 2)
                                .property(Listrecipient.CONTACTID, 3);

        MailjetResponse postResponse = client.post(postRequest);
        System.out.println(postResponse);
        
        Long ID = postResponse.getData().getJSONObject(0).getLong("ID");
        System.out.println(ID);
        
        System.out.println("PUT REQUEST");
        MailjetRequest putRequest = new MailjetRequest(Listrecipient.resource, ID)
                                .property(Listrecipient.ISACTIVE, false);

        MailjetResponse putResponse = client.put(putRequest);
        System.out.println(putResponse);
        
        System.out.println("DELETE REQUEST");
        MailjetRequest deleteRequest = new MailjetRequest(Listrecipient.resource, ID);
        
        MailjetResponse deleteResponse = client.delete(deleteRequest);
        System.out.println(deleteResponse);
    }
}
```

Let me know if you think about anything before I push this on master :)

Best,
Guillaume

**Comment by sicoa** [comment]
Good afternoon Mr Guillaume
i am very glad to tell you that delete works fine indeed. Thank you for the efforts!
How about the rest of the questions?

Remaining yours
sicoaDev

**Comment by GuillaumeBadi** [comment]
What is your goal when dealing with `listrecipient` ?

Do you want to add a `contact` to a `contactslist` ?

**Comment by sicoa** [comment]
I am trying to create one, as i described in the first question, no2 issue

**Comment by GuillaumeBadi** [comment]
If you use: `ContactManagecontactslists `, it will create the `listrecipient` automatically

``` java
request = new MailjetRequest(ContactManagecontactslists.resource, ID)
           .property(ContactManagecontactslists.CONTACTSLISTS, new JSONArray()
                                   .put(new JSONObject()
                                         .put("ListID", "$ListID_1")
                                         .put("Action", "addnoforce"))
                                    .put(new JSONObject()
                                          .put("ListID", "$ListID_2")
                                          .put("Action", "addforce")));
```

**Comment by sicoa** [comment]
I see, so ListRecipient is a part being deprecated and is almost of no use right now, is that right?

**Comment by GuillaumeBadi** [comment]
Actually no but we wouldn't recommend our users to use it because it is
complex so we created the contactManagecontactlist to make it easier

**Comment by sicoa** [comment]
Ok!
Thank you once more Guillaume!
Best wishes
sicoaDev
