### ISSUE TITLE
managecontactslists , important

### ISSUE THREAD

**Issue by sicoa** [mailjet/mailjet-apiv3-java#48]
Hello, i would like to understand how managecontactslists works and how that applies to the rest of submethods in API, used for the java wrapper.
Thank you 
sicoaDev

contact/:id/managecontactslists
Method: Create
Subscribe the contact to the given contact lists 
curl -s -X POST \
--user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
https://api.mailjet.com/v3/REST/contact/:id/managecontactslists \
-H 'Content-Type: application/json' \
-d '{"ContactsLists": ...}'
ContactsLists 	 Mandatory [ Type TContactsListActionList 

QUESTION: what is the input here? The lists' ids?

QUESTION2:
In the library implementation what should i do? 
The following does not work and it is very important to me right now:
request
{"Action":"","Filters":"{}","Action ID":0,"Resource":"contact","ID":1.......33,"Body":"{\"ContactsLists\":[{\"Action\":\"addforce\",\"ListID\":\"1\"}]}"}
response:
{"Status":405,"ErrorInfo":"","ErrorMessage":"Method not allowed","StatusCode":405}

request = new MailjetRequest(Contact.resource, contactID)
									.property(ContactManagecontactslists.CONTACTSLISTS, new JSONArray()
                                            .put(new JSONObject()
                                                    .put("ListID", listID)
                                                    .put("Action", action)));

**Comment by arnaudbreton** [comment]
Hi @sicoa,

Thanks for reaching out here again. We're glad to see you're exploring deeper and deeper our API.

About your first question, have you already visited the dedicated section for this method in our API guides? It's here http://dev.mailjet.com/guides/#managecontactslists

About your second question, can you post the full code (adding formatting, thanks to [Github flavoured Markdown](https://help.github.com/articles/github-flavored-markdown/)). Here, I'm missing the part where you're actually execute the request via `client.post(request)`.

Thanks!

**Comment by sicoa** [comment]
Thank you for the quick reply Mr Breton

I would like to see how to use the java wrapper for these functions. 
Maybe i am doing something wrong.
The client.post(request) is the exact next line :) I just omitted it considering the call granted, my bad.

Request:
{"Action":"","Filters":"{}","Action ID":0,"Resource":"contact","ID":1504485533,"Body":"{\"ContactsLists\":[{\"Action\":\"addforce\",\"ListID\":\"1\"}]}"}
Response
{"Status":405,"ErrorInfo":"","ErrorMessage":"Method not allowed","StatusCode":405} 

Code (is this correctly stated?):
```java
request = new MailjetRequest(Contact.resource, id)
									.property(ContactManagecontactslists.CONTACTSLISTS, new JSONArray()
                                            .put(new JSONObject()
                                                    .put("ListID", listsArray[i])
                                                    .put("Action", action)));
response = cl.post(request);
```

**Comment by arnaudbreton** [comment]
@sicoa, you're welcome!
Thanks for taking the time to format it correctly, appreciated!

After digging deeper here, I've figured out what's going wrong here: the resource to invoke here is not `Contact` but `ContactManagecontactslists`. This code snippet to build the request object should then work better:
```java
request = new MailjetRequest(ContactManagecontactslists.resource, ID)
                .property(ContactManagecontactslists.CONTACTSLISTS, new JSONArray()
                                 .put(new JSONObject()
                                         .put("ListID", "ListID_1")
                                         .put("Action", "addnoforce"))
                                 .put(new JSONObject()
                                        .put("ListID", "ListID_2")
                                        .put("Action", "addforce")));
```

Please let us know how this works for you!

Best,
Arnaud.

**Comment by sicoa** [comment]
It did work alright!
It needs the ID of the contact referring to ```ContactManagecontactslists.resource```. That was the missing piece. I suppose this line of thought applies to the rest of the similar calls.
Thank you very much for your accurate help.
Best wishes
sicoaDev

**Comment by arnaudbreton** [comment]
@sicoa, glad to hear it works! 

Yes, the general logic of our wrapper is to consider action endpoints (like here `/contact/:id/managecontactslists` as a resource. This logic can indeed be applied to the other available resources' actions.

Best,
Arnaud.
