### ISSUE TITLE
Attributes class change

### ISSUE THREAD

**Issue by sicoa** [mailjet/mailjet-apiv3-java#49]
In the previous API wrapper, one would use the inside attributes like Status, EditMode which would accept specific values etc like this:
Status.DRAFT__0_

How do we use them now?
Could you demonstrate by changing a Newsletter Status to Draft?

**Comment by GuillaumeBadi** [comment]
As shown [here](http://dev.mailjet.com/email-api/v3/newsletter/), the old attribute classes were just API calls. So you can use the traditional MailjetRequest to achieve that.

<img width="704" alt="screen shot 2015-12-08 at 14 28 17" src="https://cloud.githubusercontent.com/assets/6558790/11656841/fa6e3156-9db7-11e5-94b6-50bfb5a53d18.png">

``` java
        // private final int DRAFT = 0;
        client.setDebug(MailjetClient.VERBOSE_DEBUG);

        MailjetRequest request = new MailjetRequest(Newsletter.resource, ID)
                    .property(Newsletter.STATUS, DRAFT);
        System.out.println(client.put(request));
```

Best,
Guillaume

**Comment by sicoa** [comment]
Oh i see , i ll test this tommorow! Thank you very much

**Comment by sicoa** [comment]
Good morning, is this 
```java
.property(Newsletter.STATUS, DRAFT);
.property(Newsletter.STATUS, "DRAFT");```
or
```java
.property(Newsletter.STATUS, 0);```

None seem to work, especially the first case is not accepted at all as option 
What is the general case? A capital letters String value same as the reference guide? 
It used to be like ```java Status.DRAFT__0_```

**Comment by GuillaumeBadi** [comment]
The first one works, but you need to assign DRAFT/DELETED/PROGRAMMED ... with the right values showed above

```
private final int DRAFT = 0; // for instance
```

Best, 
Guillaume

**Comment by sicoa** [comment]
So it is an integer (it does allow string as well right?), 
like that i get
```
400 Invalid status transition: Not allowed to change status from 2 (sent) to 0 (draft).
```
This is a general rule?
Thank you for your insight!
Yours 
sicoaDev

**Comment by sicoa** [comment]
One more important question:
For other attributes with multiple fixed values, which are not numbered but have string values like
```
EditType 	Edit type.    [ Type AnsiString ]  Allowed values:    full    light    ulight
```
what is the call? A string with the same name?
Thank you for all the answers!

**Comment by GuillaumeBadi** [comment]
You cannot change a status from `sent` to `draft` it wont work indeed. Strings wont work in that case, sorry.

For every attribute, the wrapper will build a JSON payload like this:
``` java
.property(property, value);

// is changed to:

{
  "property": "value"
}
```
or with filters:

``` java
.filter(filter1, value1)
.filter(filter2, value2);

// is changed to:
 
String url = "https://api.mailjet.com/v3/REST/contact?filter1=value1&filter2=value2"
```

So if you see the API accepts a string for a given attribute, you will have to give it a string. As the Newsletter status accepts an `int`, we cannot provide a string.

Best,
Guillaume

**Comment by sicoa** [comment]
I see! Although when i tried it as String i got the same message, implying that it accepted somehow the String value of 0, but that is a mystery set for you :)
Thank you for everything Mr Guillaume, i appreciate it
