### ISSUE TITLE
Send API in Java Wrapper ?

### ISSUE THREAD

**Issue by Jpadilla1** [mailjet/mailjet-apiv3-java#5]
Hi,

Is there any way to use the Send API using this library?

Thanks,

**Comment by Gormador** [comment]
Hi @Jpadilla1,

Sorry for the lack of update on the matter. As you may already have found out, we implemented the send API in the Java wrapper.

Please refer to the [README](https://github.com/mailjet/mailjet-apiv3-java#46-using-the-send-api) for a step by step guide on how to use it.


I hope this helps.
Gaëtan
