### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by sicoa** [mailjet/mailjet-apiv3-java#51]
Hello once more and thank you in advance for your insight.
I have been involved with testing the filters right now and i got an issue, which i believe we have discussed a bit before but i have lost it. Maybe i am doing something wrong..
I am trying by the wrapper and by curl and although i have 4 campaigns at SENT ,
i get as result all campaigns that i have constructed

curl:
```
https://api.mailjet.com/v3/REST/campaignstatistics?Sent=true
```
java
```java
request = new MailjetRequest(Campaignstatistics.resource);
request.filter(Campaignstatistics.SENT, sentfilter); //sentfilter: String set as "true". Boolean not allowed
response = cl.get(request);
```
the request:
```
{"Filters":"{Sent=true}","Body":"{}","Resource":"campaignstatistics","ID":0,"Action ID":0}
```
Response: All Campaignstatistics

**Comment by GuillaumeBadi** [comment]
You code works in my case actually:
``` java
        MailjetRequest request = new MailjetRequest(Campaignstatistics.resource)
                .filter(Campaignstatistics.SENT, "true")
                .filter(Campaignstatistics.COUNTONLY, 1);
        
        MailjetResponse response = client.get(request);
```
``` java
{"Status":200,"Data":[],"Count":373,"Total":373}
```

``` java
        MailjetRequest request = new MailjetRequest(Campaignstatistics.resource)
                .filter(Campaignstatistics.SENT, "false")
                .filter(Campaignstatistics.COUNTONLY, 1);
        
        MailjetResponse response = client.get(request);
```

``` java
{"Status":200,"Data":[],"Count":65,"Total":65}
```

**Comment by sicoa** [comment]
I see, then maybe i have understood something wrong about what the filter really does,,,
Thank you, maybe if i encounter an issue later on i ll come back 
Good afternoon!

**Comment by GuillaumeBadi** [comment]
Filters are used to add informations about your `GET` requests. So when you are making a `GET` on `Contacts` for example, you can say either 'list me every contact', or 'list me every contact with this status' or 'list me every contact with this email adress' (so it will output only one contact).

Best,
Guillaume
