### ISSUE TITLE
MessageStatistics ID

### ISSUE THREAD

**Issue by sicoa** [mailjet/mailjet-apiv3-java#52]
Greetings once more
The reference states:
```
Access a given messagestatistics resource, use a GET request, providing the messagestatistics's ID value. 
```
However, i do not know where to acquire the ID from. Messagestatistics List function unfortunately does not return an ID..
Thank you for any reply
Yours 
sicoaDev

**Comment by GuillaumeBadi** [comment]
retrieve it with a `List` using filters like your campaignID, it will return a single result
