### ISSUE TITLE
MailjetClient uses GET instead of DELETE for delete operation

### ISSUE THREAD

**Issue by svenfrauen** [mailjet/mailjet-apiv3-java#55]
Dear Mailjet team,

thanks for the great Java API Wrapper!
When I tested it I recognized that the DELETE method in the MailjetClient class uses a GET operation instead, which does not fit your API description.

You can find it here: https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/MailjetClient.java#L199

Cheers,
Sven

**Comment by GuillaumeBadi** [comment]
Hey @svenfrauen !

Thanks for discovering the typo! It is fixed!

Can you make sure it works on your side ? 

Regards,
Guillaume

**Comment by svenfrauen** [comment]
Hey @GuillaumeBadi !
Thanks a lot, it's working now!

Regards,
Sven
