### ISSUE TITLE
Exceptions and logger

### ISSUE THREAD

**Issue by laurent-dol** [mailjet/mailjet-apiv3-java#57]
Hello,

For exemple, if there is a java.net.SocketTimeoutException, we get a nullpointer and the socketTimeoutException is logged in the console.

The MailjetClient should throwned all exceptions, as this we can catch and log them, and we can manage retries (depends on the error).

**Comment by GuillaumeBadi** [comment]
Hey @laurent-dol !

The client throws MailjetExcpetions for mostly internals excpetions.
But I dont think it ignore some errors by printing them. What is your code?

**Comment by laurent-dol** [comment]
If you look at AbstractHttpClient.execute (called by post, get, ...) , exceptions are stored in a requestHandler. In case of BasicHttpClient, the requestHandler used is BasicRequestHandler that prints errors in console.

**Comment by GuillaumeBadi** [comment]
What about being able to provide a custom Handler to the MailjetClient's constructor ?
like : https://github.com/mailjet/mailjet-apiv3-java/pull/58

**Comment by laurent-dol** [comment]
My need goes further than exception management.

I'm writing a MailjetClient based on Apache HttpClient and not turbomanage, in order to manage connections pool, exception management, retries,...

To do this, I have only to modify MailjetRequest to get _filters outside of the package. (If a getFilter is added, it could be great).

Also, the Mailjet API should be modified to invite to do own implements. The first thing should be to add a MailjetClientInterface that i could implement with my own http client.
I purpose to modify MailjetException too, in order to add in the constructor the origin exception, so all methods of MailjetClient interface throw only MailjetException.

**Comment by GuillaumeBadi** [comment]
Hey ! I am closing it for now as the wrapper re-implementation is not on the roadmap yet.
