### ISSUE TITLE
NullPointerException in MailjetResponse when a request results in an error

### ISSUE THREAD

**Issue by aeons** [mailjet/mailjet-apiv3-java#59]
Hello,

When a request, eg. a POST, using MailjetClient fails, the response body is null, and this gets converted into the JSON string "{}". (see https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/MailjetClient.java#L159)

Then a MailjetResponse is created, using the empty JSON object as the parameter obj. This makes calls to `getTotal` and `getCount` fail with an NPE. This is in my opinion a very brittle solution. Instead of just storing the raw JSON in the response, it should probably be parsed and stored as real variables.

Additionally:
Why are the binary build artifacts included in the repository?
Is there a reason this library is not published anywhere?

**Comment by GuillaumeBadi** [comment]
Hey @aeons !

I agree with that.
Actually it is not when the client fails but when the API does not send any content back to the client. But yes the response should at least contain the status code to check for error. When you say parsed and stored, what do you mean ?

**Comment by aeons** [comment]
I mean that in the constructor for MailjetResponse, the JSONObject is parsed and variables total and count are created and stored on the object, with a value of 0 (or something) if the variable is not present in the JSON. This way you get around having to check for NPEs before calling `getTotal/getCount`.

**Comment by GuillaumeBadi** [comment]
Ok I came up with this to prevent the client from throwing NPEs https://github.com/mailjet/mailjet-apiv3-java/pull/60

**Comment by aeons** [comment]
It looks somewhat like what I was thinking of.

I think you need to wrap the `getInt/getString/getJSONArray` methods with a `_rawResponse.has` call, otherwise you will still get NPE if you call `getInt` with a key that is not in the `_rawResponse`.

**Comment by GuillaumeBadi** [comment]
Actually, fot getString, if it does not have the field, I don't think it should return an empty string it would be bad, same as getint, that should not return 0 if the key does not exists, what do you think ?

**Comment by aeons** [comment]
Yes, but then I guess the methods should have a throws clause to the methods so you are sure the potential NPE will be checked on the caller's side.

**Comment by GuillaumeBadi** [comment]
I am throwing a MailjetException with the last commit
