### ISSUE TITLE
Maven central ? 

### ISSUE THREAD

**Issue by jblezoray** [mailjet/mailjet-apiv3-java#61]
Hi,

Do you plan to release this lib to maven central ? It would make its integration much easier for us. 

regards, 
JB.

**Comment by GuillaumeBadi** [comment]
Hey ! I created a ticket in order to achieve that! https://issues.sonatype.org/browse/OSSRH-21130 . Keep you up to date

**Comment by jblezoray** [comment]
Great, thank you!

**Comment by rschreijer** [comment]
+1 ... that'd be great.

**Comment by florent-blanvillain** [comment]
Hi,

The ticket is now resolved. Did you have a chance to upload the artifacts ?

**Comment by mariomatar** [comment]
+1

**Comment by GuillaumeBadi** [comment]
Sorry for the delay guys, we had a lot to do recently, can you check it work on you side ? The artifact should be resolved by maven in about 2hours
