### ISSUE TITLE
Contacts CSV upload

### ISSUE THREAD

**Issue by GregoryEstienne** [mailjet/mailjet-apiv3-java#62]
Hello,

The code sample to "Add Contacts in bulks" (https://dev.mailjet.com/guides/?java#add-contacts-in-bulks) for the CSV upload does not seem correct: Csvimport.DATA does not exist in the Java API wrapper. I tried with the string "Data" (instead of Csvimport.DATA) but my request returns a 405: Method not allowed. I tried with a java.io.File and a java.lang.String to provide the CSV file ("MYFILE"), same result.

Could you help me with this issue? I tried to contact the official support, see Ticket #432541 if you have access to them, and Mike P. told me to seek for help here, because my problems seem to be specifically related to the wrapper...

Thanks!

**Comment by GuillaumeBadi** [comment]
Hey @GregoryEstienne 

I am a little bit struggling on that, but be aware I am on it ;)

**Comment by GregoryEstienne** [comment]
Hi Guillaume!

Thanks for following up!

Don't worry, I'm fine with the other way to add contacts in bulk ("/contact/managemanycontacts", the other issue you resolved already). I mean it is not urgent for us anymore :)

**Comment by Zhivko-Mailjet** [comment]
@GregoryEstienne The modifications to the wrapper have been done while ago. Feel free to reopen the issue in case you have any additional questions.
