### ISSUE TITLE
Add Contacts in bulks using "/contact/managemanycontacts"

### ISSUE THREAD

**Issue by GregoryEstienne** [mailjet/mailjet-apiv3-java#63]
Hello,

I tried to add contacts in bulks using "/contact/managemanycontacts" (https://dev.mailjet.com/guides/?java#contact_managemanycontacts), but the sample provided, as well as my code, returns a 400: Invalid json input: object ""->"TContact" has no property "ContactsLists"

Could you help me with this issue?

Thanks!

**Comment by GuillaumeBadi** [comment]
Hey ! Can you paste your code here so I can try it on my side ?

**Comment by GregoryEstienne** [comment]
Hi Guillaume!

Sure! But it's really the code sample provided on the website: https://dev.mailjet.com/guides/?java#contact_managemanycontacts

Thanks!

`package com.my.project;

import org.json.JSONArray;
import org.json.JSONObject;

import com.mailjet.client.MailjetClient;
import com.mailjet.client.MailjetRequest;
import com.mailjet.client.MailjetResponse;
import com.mailjet.client.resource.ContactManagemanycontacts;

public class ContactListManager {

	/**
	 * Create : Manage the details of a Contact.
	 * 
	 * @throws Exception
	 */
	public static void main(String[] args) throws Exception {
		if (args == null || args.length < 3) {
			throw new IllegalArgumentException("Please provide:  a Contact List ID");
		}

		System.out.println("API Public Key: " + args[0]);
		String mailjetApiPublicKey = args[0];

		System.out.println("API Private Key: " + args[1]);
		String mailjetApiPrivateKey = args[1];

		System.out.println("Contact List ID: " + args[2]);
		long contactListId = Integer.valueOf(args[2]);

		MailjetClient client;
		MailjetRequest request;
		MailjetResponse response;
		client = new MailjetClient(mailjetApiPublicKey, mailjetApiPrivateKey);
		request = new MailjetRequest(ContactManagemanycontacts.resource)
				.property(ContactManagemanycontacts.CONTACTSLISTS,
						new JSONArray().put(new JSONObject().put("ListID", contactListId).put("action", "addnoforce")))
				.property(
						ContactManagemanycontacts.CONTACTS,
						new JSONArray().put(
								new JSONObject()
										.put("Email", "jimsmith@example.com")
										.put("Name", "Jim")
										.put("Properties",
												new JSONObject().put("Property1", "value").put("Property2", "value2")))
								.put(new JSONObject()
										.put("Email", "janetdoe@example.com")
										.put("Name", "Janet")
										.put("Properties",
												new JSONObject().put("Property1", "value").put("Property2", "value2"))));
		response = client.post(request);

		if (response.getStatus() != 201) {
			throw new Exception("StatusCode: " + response.getStatus() + ". ErrorMessage: "
					+ response.getString("ErrorMessage"));
		}

		System.out.println(response.getStatus());
		System.out.println(response.getData());
	}
}

[ContactListManager.java.zip](https://github.com/mailjet/mailjet-apiv3-java/files/169539/ContactListManager.java.zip)
`

**Comment by GuillaumeBadi** [comment]
Meged! Can you try on your side ? :)

**Comment by GregoryEstienne** [comment]
Excellent! That works fine now!

Thanks for your help and your quick answer!
