### ISSUE TITLE
Create a Newsletter - sample code does not compile - "Invalid json input" error

### ISSUE THREAD

**Issue by GregoryEstienne** [mailjet/mailjet-apiv3-java#64]
Hi Guillaume!

I found another problem, in the "Create a Newsletter" sample code (https://dev.mailjet.com/guides/?java#prepare-a-newsletter).

The code does not compile because "Newsletter.CONTACTSLISTID" cannot be resolved / does not exist. I tried with "Newsletter.CONTACTSLIST" without success, I get an "Invalid json input" error.

I compared the properties of the "newsletter" from the API doc (https://dev.mailjet.com/email-api/v3/newsletter/) and your implementation (https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/resource/Newsletter.java) and I don't find them matching, maybe there is a problem there?!

Thanks for your help!

**Comment by GuillaumeBadi** [comment]
I added the property in the newsletter resource, sorry about that! Can you try on your side ?

**Comment by GregoryEstienne** [comment]
Thank you! That works fine now!
