### ISSUE TITLE
Search contact by email

### ISSUE THREAD

**Issue by driccio** [mailjet/mailjet-apiv3-java#67]
Hi,

Seems the java API doesn't allow to make the equivalent curl request to find a contact by email:
`curl -s -X GET --user "PUBLI_KEY:PRIVATE_KEY" "https://api.mailjet.com/v3/REST/contact/test@test.com"`

http://dev.mailjet.com/email-api/v3/contact/

If I'm wrong please tell me how to do.

Thanks,

Damien

**Comment by driccio** [comment]
Maybe an ugly workaround that will work (don't tested yet):
`new MailjetRequest(new Resource("contact", email))`

Create a specific Resource object where action is the email.

**Comment by GuillaumeBadi** [comment]
Hey @driccio !

I am on it ! I don't think I am going to use this trick though ;)

**Comment by GuillaumeBadi** [comment]
It should now be fixed: https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/MailjetRequest.java#L125

**Comment by driccio** [comment]
Thanks :+1:
