### ISSUE TITLE
NPE when offline

### ISSUE THREAD

**Issue by emu42** [mailjet/mailjet-apiv3-java#68]
I discovered an exception handling issue when my network connection went down. This caused an uncaught NullPointerException where I would have expected to see a mere MailjetException. 

The BasicHttpClient.post(..) method returns null instead of a proper response object in this case (dropping the "java.net.UnknownHostException: api.mailjet.com"), and MailjetClient does not check for a null-response there.

**Comment by GuillaumeBadi** [comment]
Hey @emu42 

Thanks for reporting this.
This should now be caught with: https://github.com/mailjet/mailjet-apiv3-java/commit/d7730d39fde12d972384e9c6c36193a7f10ec4a8

Can you confirm it works on your side?

Regards,
Guillaume

**Comment by GuillaumeBadi** [comment]
I am closing this right now, please reopen if you have anything to add to it

**Comment by emu42** [comment]
Sorry I did not get to test this earlier. Works fine now. Thanks!
