### ISSUE TITLE
no error but no email

### ISSUE THREAD

**Issue by syronanm** [mailjet/mailjet-apiv3-java#69]
Hi,

I'm using your API but when i call :

 client.createCall(SendMessage.Create)
	              .property(SendMessageProperty.FROMEMAIL, emailing.getHeaderSenderEmail())
	              .property(SendMessageProperty.SUBJECT, emailing.getHeaderSubject())
	              .property(SendMessageProperty.TEXTPART, " BLABLABLA ") 
	              .property(SendMessageProperty.RECIPIENTS, recipients)
	              .execute();

I have no issue but i don't get any mail either...

In the console there is 2 lines :

1) MailJetApiResponse execute called

2) Response = HTTP/1.1 200 OK [Server: nginx, Date: Wed, 27 Apr 2016 17:19:35 GMT, Content-Type: application/json, Content-Length: 82, Connection: keep-alive]

2 remarks :
* the Date is 2 hours late
*  the behavior of the application is the same if i use "https://api.mailjet.com/v3/REST" or ""https://api.mailjet.com/v3/"

Do you have any idea ?

Thanks,

**Comment by GuillaumeBadi** [comment]
Hey ! Thanks for using mailjet!

You are using an old version of the wrapper that is not maintained anymore. I highly encourage you to use the last release. It has a debug mode for you to better understand issues like that, and it is available on maven central as well as github on master (within this repository)

Guillaume

**Comment by syronanm** [comment]
Thanks for answering this quick !

I had just realized that i used an old version.

**Comment by GuillaumeBadi** [comment]
Does it work for you now ?

**Comment by syronanm** [comment]
Yes it works thanks,

By the way, One more question :)

I would like to change the sender email shown in the mail box.

I tried Email.HEADERS with  "Reply-To" (like in the example) but it doesn't seem to work. How can i do ?

**Comment by GuillaumeBadi** [comment]
Not sure I understand what you are looking for, but you can try Email.FromName, to change the Email Name, and for the reply-to:
``` java
.property(Email.HEADERS, new JSONObject()
     .put("Reply-To", "copilot@mailjet.com"));
```

**Comment by syronanm** [comment]
That's what i did but the sender email seen by those who get the email stay Email.FromEmail

**Comment by GuillaumeBadi** [comment]
``` java
MailjetRequest email;
JSONArray recipients;
MailjetResponse response;

recipients = new JSONArray()
                .put(new JSONObject().put(Contact.EMAIL, "roger@mailjet.com"))
                .put(new JSONObject().put(Contact.EMAIL, "stan@mailjet.com"))
                .put(new JSONObject().put(Contact.EMAIL, "francine@mailjet.com"));

email = new MailjetRequest(Email.resource)
                    .property(Email.FROMNAME, "Guillaume")
                    .property(Email.FROMEMAIL, "dummy@email.fr")
                    .property(Email.SUBJECT, "Subject")
                    .property(Email.TEXTPART, "Java is coming!...")
                    .property(Email.RECIPIENTS, recipients)
                    .property(Email.MJCUSTOMID, "JAVA-Email")
                    .property(Email.HEADERS, new JSONObject()
                          .put("Reply-To", "copilot@mailjet.com"));

response = client.post(email);
```

What do you get when using this code ? (with your sender email in FromEmail, and Recipients of course)

**Comment by syronanm** [comment]
That's exactly what i did,

I get a message from "Guillaume , dummy@email.fr" in my "roger@mailjet.com" box.

But i want a mail from "Guillaume, copilot@mailjet.com"

**Comment by GuillaumeBadi** [comment]
The best you can do is this
![screen shot 2016-04-29 at 11 00 26](https://cloud.githubusercontent.com/assets/6558790/14912017/ae9fd308-0df9-11e6-8233-7483f5827c78.png)

You can not fake a ender email if it is not a registered email address. The only thing that you can do is setting a reply-to email in order to get the user reply to a specific address when hitting `reply`

**Comment by Benoit-amo** [comment]
Java is... what ? :)

**Comment by syronanm** [comment]
ok sorry i thought we could fake an ender email.

Thanks for your involvment and sorry for my misunderstanding

**Comment by GuillaumeBadi** [comment]
@Benoit-amo Game of Thrones fans will understand ;)

**Comment by nurbek-b** [comment]
@WeshGuillaume on python I am gettin' response code 200, but the message has not sent.
