### ISSUE TITLE
Getting 400 error, with no body to explain why

### ISSUE THREAD

**Issue by zirxcorporation** [mailjet/mailjet-apiv3-java#70]
Hi There- 

I've recently signed up with MailJet and was hoping to use the Java client... unfortunately I keep getting an empty 400 HTTP code... here's a snippet of my code, would love any help debugging.

For background, I was able to successfully use the curl command to send e-mails... and my domains are fully SPF'd and DKIM'd.
```
public static void sendEmail(String from, List<String> toList, String subject, String body, String type) {
    MailjetRequest email;
    JSONArray recipients;
    MailjetResponse response = null;

    recipients = new JSONArray();
    for (String recipient: toList) {
      recipients.put(new JSONObject().put(Contact.EMAIL, recipient));
    }

    email = new MailjetRequest(Email.resource)
      .property(Email.FROMNAME, "ThePlatform")
      .property(Email.FROMEMAIL, from)
      .property(Email.SUBJECT, subject)
      .property(Email.RECIPIENTS, recipients)
      .property(Email.HTMLPART, body); 

  try {
        response = client.post(email);
    } catch (Exception e) {
      Logger.error(String.format("Failed to send/save [%s] to [%s] because of exception", subject, toList), e);
    }
}
```

The response I get back has no Data property... so not sure what I'm doing wrong :(

**Comment by GuillaumeBadi** [comment]
Hey ! 

Can you try to activate the verbose debug mode ?
`client.setDebug()`

**Comment by zirxcorporation** [comment]
Yep- Using the same code above with verbose I get the following output in the logs -

```
=== HTTP Request ===
POST https://api.mailjet.com/v3/send
Accept-Charset:UTF-8
Accept:application/json
user-agent:mailjet-apiv3-java/v3.1.1
Content-Type:application/json
=== HTTP Response ===
Receive url: https://api.mailjet.com/v3/send
Status: 400
null:HTTP/1.1 400 Missing "To" or "Recipients" property
Server:nginx
Connection:keep-alive
Vary:Accept-Encoding
Content-Length:0
Date:Mon, 02 May 2016 16:06:39 GMT
Content-Type:text/html
Content:
null
```

However, I'm setting the Recipients parameter as shown in the Java example here (http://dev.mailjet.com/guides/?java#sending-a-basic-email).  I'll keep fiddling with this, but would love any guidance you can offer!

Thanks!

**Comment by GuillaumeBadi** [comment]
The code looks good to me as well. Can you print out recipients to the console before making the call to ensure it is passed correctly

**Comment by zirxcorporation** [comment]
Ah- that fixed it... I was accidentally importing `com.amazonaws.util.json.JSONArray`, instead of `org.json.JSONArray` and that seems to have been giving invalid JSON

Thanks Guillaume!  Apologies for the silly problem-

**Comment by GuillaumeBadi** [comment]
That's ok, glad it works for you ! :)
