### ISSUE TITLE
java null exception

### ISSUE THREAD

**Issue by syronanm** [mailjet/mailjet-apiv3-java#71]
Hi,

I wrote a code very similar to your exemple [ http://dev.mailjet.com/guides/?java#sending-a-basic-email ] in order to send an email.

It works fine in my computer [both in eclipse and directly in Tomcat] but when i copy the war in an other tomcat's computer the .post() send a java error [java null exception]

It came from the .execute function of the AbstractHttpClient class (in the turbomanage API)

Do you have any idea about this bug ?

Thanks,

Ronan

**Comment by syronanm** [comment]
obviously i was wrong : it's not the .execute() function who is involved

I add "client.put(email);" just before the "client.post(email)" and i have the same issue : everything works fine in my computer and, in the server, i have the same error : 

java.lang.NullPointerException: null
	at com.mailjet.client.MailjetClient.put(MailjetClient.java:206) ~[mailjet-parent-4.0.1.jar:na]

**Comment by GuillaumeBadi** [comment]
I can't find a way to reproduce the error except when my connection is off, are you sure you are allowed to trigger http requests on your server ?

**Comment by syronanm** [comment]
It might be an issue with HTTPS . maybe a too restrictive certificate check.

Can i switch between HTTP and HTTPS in the mailjet API ?

**Comment by GuillaumeBadi** [comment]
Maybe. It is set to [https by default](https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/MailjetClient.java#L44). can you git clone it and manually check by changing the corresponding line ?

**Comment by syronanm** [comment]
Sorry, I forgot to answer.

The cacert file wasn't goot si i had to change my version of java
