### ISSUE TITLE
MailjetRequest#getBody returns empty string before posting

### ISSUE THREAD

**Issue by seahrh** [mailjet/mailjet-apiv3-java#73]
I wanted to log the email content **before** sending the email. That's because sending email could possibly throw an exception and thus, the log statement would never be reached. Email was sent successfully but the log shows an empty string for both #getBody and #toString. Is this expected behaviour?

```
MailjetRequest email = new MailjetRequest(Email.resource).property(
                Email.FROMEMAIL, senderAddress)
    .property(Email.FROMNAME, senderName)
    .property(Email.SUBJECT, subject)
    .property(Email.TEXTPART, textPart)
    .property(Email.HTMLPART, htmlPart)
    .property(Email.RECIPIENTS, recipients);
log.info("Email body:\n", email.getBody()); // Empty string
log.info("Email body:\n", email.toString()); // Empty string
try {
    // trigger the API call
    MailjetResponse rsp = client.post(email);
    // Read the response data and status
    log.info("Status [{}]\nData[{}]", rsp.getStatus(), rsp.getData()); // Output OK
} catch (MailjetException | MailjetSocketTimeoutException e) {
    throw new ServletException(e);
}
```

**Comment by Zhivko-Mailjet** [comment]
@seahrh 

Sorry for the delayed answer, I was running some tests and was able to print the content in the console. Example:

`     System.out.print("Email body:\n" + request.getBody()); // Empty string
      System.out.print("Email body:\n" + request.toString()); // Empty string
      response = client.post(request);
      System.out.println(response.getStatus());
      System.out.println(response.getData());`

If this is not helping, could you please specify where would you like to log the details ? I believe some context of what you are trying to achieve will be useful for us to help.

**Comment by Zhivko-Mailjet** [comment]
@seahrh Since I haven't heard back from you, I will proceed to closing the issue for now. If you have additional questons, feel free to reopen it anytime.
