### ISSUE TITLE
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

### ISSUE THREAD

**Issue by agsola** [mailjet/mailjet-apiv3-java#74]
Using Google AppEngine (GAE) I'm having an exception which prevents me from sending an email.

I'm using 4.0.5 version from Maven.
Trying to send as in the example

JSONArray recipients;
recipients = new JSONArray()
                .put(new JSONObject().put(Contact.EMAIL, "mail1@gmail.com"))
                .put(new JSONObject().put(Contact.EMAIL, "mail2@gmail.com"));

email = new MailjetRequest(Email.resource)
                    .property(Email.FROMNAME, "Guillaume")
                    .property(Email.FROMEMAIL, "test@mydomain.com")
                    .property(Email.SUBJECT, "Subject")
                    .property(Email.TEXTPART, "Java is coming!...")
                    .property(Email.RECIPIENTS, recipients)
                    .property(Email.MJCUSTOMID, "JAVA-Email");

But I get this error:

org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
at com.mailjet.client.MailjetClient.post (MailjetClient.java:197)
at MYCLASS.sendSimpleMessageUsingMailjet (MailAuxiliar.java:70)

Line which correspond to the
 		      MailjetResponse response = client.post(email);
line.

I've tried setting the recipients manually using JSON, but doesn't seem to be related with that, or changing every property to different values.
Still, no changes...

**Comment by Zhivko-Mailjet** [comment]
@agsola 

We haven't been able to reproduce the issue on our end yet. Could you try with the samples in this documentation and let me know whether it will work for you - https://dev.mailjet.com/guides/?java#sending-a-basic-email

**Comment by agsola** [comment]
I've found the error.
The API wasn't properly sent. But the error is not very verbose...

**Comment by Zhivko-Mailjet** [comment]
Hi @agsola,

I'm happy that you found the error. Could you please share some more details what exactly was the root cause of the error and how you corrected it, so we can work on having more explicit error description ?

**Comment by fleske** [comment]
Hello,

I've got the same issue and it happens only sometimes randomly.
Code is exactly the same as in the README.md from this github page, any ideas?
