### ISSUE TITLE
Handle proxy context

### ISSUE THREAD

**Issue by Benoit-amo** [mailjet/mailjet-apiv3-java#75]
It's a big issue for us, it seems that the lib does not handle proxy context.
We do not found any information about it into the sources, neither into the basic-http-client dependency.

**Comment by Zhivko-Mailjet** [comment]
@Benoit-amo 

At this point, we do not have proxy support in our wrapper. This is definetely something that will come in future, but we can not estimate any time frame for now.

P.S. We are open for any contribution

**Comment by Benoit-amo** [comment]
Yes, and we store the current values of those properties temporarily, so we can restore them after calling the MJ API. Not sexy, but acceptable.

**Comment by ddamyanova** [comment]
Hi @Benoit-amo ,

If your question was answered, please close this issue.

Thank you,
Desislava

**Comment by mskochev** [comment]
Closing this issue, because an acceptable solution has been found.
