### ISSUE TITLE
Filter on GET "v3/REST/eventcallbackurl" does not work

### ISSUE THREAD

**Issue by hennroja** [mailjet/mailjet-apiv3-java#79]
I am sending this request:
```java
MailjetRequest request = new MailjetRequest(Eventcallbackurl.resource)
				.property(Eventcallbackurl.VERSION, 2)
				.filter(Eventcallbackurl.EVENTTYPE, type);
```
It should be analog to this calling url:
`https://api.mailjet.com/v3/REST/eventcallbackurl?EventType=open`

The filter is not applied. All 10 types are shown.
![screen shot 2017-11-02 at 16 44 08](https://user-images.githubusercontent.com/2955243/32336195-f13fd886-bfee-11e7-922d-491ec1f1d411.png)

Is it a bug or a feature ? Or do I simply use it wrong ?

**Comment by latanasov** [comment]
Hi @hennroja it seems there is a bug in the API with the "open" EventType filter only (the rest work). I've reported the issue and we'll have it fixed. My apologizes for the inconvenience.

**Comment by latanasov** [comment]
Closing this one on Github- will be handled by our API team.

**Comment by hennroja** [comment]
Thanks to you and the team !

Would be helpful when you write usw a comment when the change is released.
