### ISSUE TITLE
How to add contact to existing list ?

### ISSUE THREAD

**Issue by iset2012** [mailjet/mailjet-apiv3-java#8]
Hi,
I can't figure out how to get contact (email) ID and add it to an existing list (with given ID) ! 
I foudn this : https://app.mailjet.com/docs/api/lists/addcontact ... but I don't see how can I do it in Java :(
Regards :)

**Comment by arnaudbreton** [comment]
Hi @iset2012,

The documentation you're referring to is for a deprecated version of our API. The current version is here: https://dev.mailjet.com. 

The guide which is interesting for you is this one: http://dev.mailjet.com/guides/contact-list-guide/

Hope it helps!
Arnaud.

**Comment by iset2012** [comment]
Thanks for the answer, but I still can't see how to do it with the java API, I tried the code below but I can't run it : 

            ListRecipient c;
            c = client.createCall(ListRecipient.Update)
                    .property(ContactProperty.ID, "foo@bar.com")
                    .property(ListRecipient.ListID, 1)
                    .execute();
There are errors int property method !

**Comment by arnaudbreton** [comment]
Hey, 

Sorry for the delay in my answer. You need to first `GET` the `ListRecipient` entity matching your criterias, using the [filters](http://dev.mailjet.com/email-api/v3/listrecipient/#filters) `ContactEmail` and `ContactsList`. Then, you can update it using the ID you got.

Hope it helps.
Arnaud.

**Comment by arnaudbreton** [comment]
@iset2012, I'm closing this issue for the moment. Don't hesitate to re-open it or open another one if you're still experiencing issues.

Best.
