### ISSUE TITLE
On GET "v3/REST/eventcallbackurl"  EventType blocked is missing.

### ISSUE THREAD

**Issue by hennroja** [mailjet/mailjet-apiv3-java#80]
Hey!
In the documentation I read that you have 11 eventtypes:
```java
String[] eventTypes = {"open", "click", "bounce", "spam", "blocked", "unsub",
			"typofix", "sent", "parseapi", "newsender", "newsenderautovalid"};
```
I was able to set all eventcallbackurls. On `https://app.mailjet.com/account/triggers` I can not see all but at least 7. Including `blocked`.

When I call:
`https://api.mailjet.com/v3/REST/eventcallbackurl?eventType=blocked`
I get the eventcallbackurl for the eventtype `blocked`

When I call:
`https://api.mailjet.com/v3/REST/eventcallbackurl`
I get all eventcallbackurls, except `blocked`. Thats strange!

Hope you can reproduce that.

**Comment by latanasov** [comment]
Hi @hennroja, it seems that the API Reference is out-of-date, so we will have this fixed. The available eventTypes are:
```
open
click
bounce
spam
blocked
unsub
sent
```
I did not manage to reproduce your second issue, I do see `blocked` events when I call `https://api.mailjet.com/v3/REST/eventcallbackurl` . You are only receiving the first 10 results, are you sure `blocked` are simply not in this set ?

**Comment by hennroja** [comment]
OK only the first 10 could explain the issue. So can we increase so 15 ?
Or what is the recommended way to get all ?

**Comment by latanasov** [comment]
Hi @hennroja  you can increase the [Limit ](https://dev.mailjet.com/guides/#the-limit-filter) filter. Or navigate through the full set of results using [this ](https://dev.mailjet.com/guides/#navigation-through-results) approach.

**Comment by hennroja** [comment]
I will try this thanks !
