### ISSUE TITLE
Typo in ErrorMessage: "Uknwown event null"

### ISSUE THREAD

**Issue by hennroja** [mailjet/mailjet-apiv3-java#81]
Sorry I feel bad for reporting this one ;-) but we your your API a lot and we need it to be perfect.
Found an typo in ErrorMessage: "Uknwown event null". 
To find it quickly:
```bash
grep "Uknwown event" -r .
```
![screen shot 2017-11-02 at 16 00 06](https://user-images.githubusercontent.com/2955243/32383329-031fdd52-c0b8-11e7-9ad1-8b428e08ce94.png)

**Comment by latanasov** [comment]
Hi @hennroja, thank you for reporting this issue. I'll forward it to the responsible people.

**Comment by mskochev** [comment]
Hello @hennroja, I would like to bring that issue back to life and see if it is still being a problem. We investigated on Mailjet side but cannot reproduce the error with the typo. Please if it is still occurring for you, provide us more detail about the request that leads to that error so we can solve it.

Thanks!

**Comment by hennroja** [comment]
I can not say if this is still an issue. 

Its to long ago. You If you can not find the typo in your codebase it should be fine.

On the other hand I can not imagin' that it is a decoding mistake in IntelliJ.

Feel free to close this issue.
