### ISSUE TITLE
Setting zero into a float contact property

### ISSUE THREAD

**Issue by luchoct** [mailjet/mailjet-apiv3-java#83]
Hi,
I have defined several contact properties with MarketJet UI. One of them is a decimal property, i.e. invoking GET over contactmetadata resource returns something like following block: 
`Datatype: "float"
Name: "balance"
ID: XXXXX
NameSpace: "static"`

When I create a contact with `contactslist/:id/managecontact` resource, sending the properties on ContactslistManageContact.PROPERTIES, **it creates the contact with all property values when value of this float property is not zero**, i.e. `BigDecimal("10.32")`, `BigDecimal("5.37")`, etc., as the contact is created and added to the list, and after checking in the MailJet web admin tool, values are properly assigned to the properties

However, **sending a zero value**, i.e. `BigDecimal("0.00")`, `BigDecimal("0")`, etc. **returns following error**
`{ "ErrorMessage" : "Object properties invalid", "StatusCode" : 400, "ErrorInfo" : { "Properties" : [{ "balance" : "Property type does not match definition" }] } }`

This is only happening on creating the contact and adding it to the list, since **updating the property value** (PUT over contactdata resource) **works well with zero and non zero values** (sending appropriate BigDecimal object as part of Contactdata.DATA).

Is this a bug or should I send zero values in a different way?

**Comment by mskochev** [comment]
This issue has been resolved in v. 4.2.1 of the wrapper.
