### ISSUE TITLE
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1] 

### ISSUE THREAD

**Issue by shilpidas27** [mailjet/mailjet-apiv3-java#84]
I am trying to send mails from Google App Engine using Mailjet client.

I'm using Mailjet version 4.0.5.

I am using a suspended mailjet account to send the mail. 
I have used `post` method of `MailjetClient` class for the same. But I get the following error:
```
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:197)
```

The error is received because body of response is empty and hence the json created from the body of the response is also empty (line number 195 of `com.mailjet.client.MailjetClient.java`) which justifies the above error.

The status code of the response received is 401 which is correct .
The exception thrown doesn't give any information about invalid account rather it says JSONException which is not the root cause of the error.

Is my understanding correct? What should be done to handle this kind of scenario (where account gets suspended for some reason)?

PS: I have tried Mailjet version 4.1.1 as well but faced the same issue.

**Comment by fleske** [comment]
I have the same issue but randomly.
I'm using the library directly (no Google App Engine) and this error happens sometimes.
Mailjet version is 4.1.1, this is the line of code in MailjetClient:
`json = (response.getBodyAsString() != null ?
                    response.getBodyAsString() : new JSONObject().put("status", response.getStatus()).toString());
            return new MailjetResponse(response.getStatus(), new JSONObject(json));`

response.getBodyAsString() returns an empty string (not null) and then new JSONObject(json) throws following error:

`org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:197)`

I'm using the library like in the example here on github and it works - this error happens sometimes and I've checked the email address which seems valid. 
This exception should be handled in MailJetClient

**Comment by myxibrium** [comment]
I am also following the example from Github directly. And always getting the error. I agree that the client should handle the error.

org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433) ~[json-20140107.jar:na]
	at org.json.JSONObject.<init>(JSONObject.java:194) ~[json-20140107.jar:na]
	at org.json.JSONObject.<init>(JSONObject.java:321) ~[json-20140107.jar:na]
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:218) ~[classes/:na]

**Comment by osigida** [comment]
Is there any plans to fix the error? It makes the Java lib unusable.

**Comment by abedurftig** [comment]
Hello, +1 from me. 

Currently the Java library cannot be used. The response I am getting when using Curl (with my Java generated payload) is actually valid JSON. Please fix it.

**Comment by abedurftig** [comment]
Update: So turns out I was using version 3 of the API in my Java client and version 3.1 when using Curl. The solution was to pass ClientOptions, when instantiating the MailjetClient.

**Comment by mskochev** [comment]
The issue has been resolved, so I am closing this thread.

**Comment by lukasz-gosiewski** [comment]
Lib still unusable as fixed version was not published on repos.

**Comment by quinao** [comment]
Hello,

I'm getting the same error when trying to create a contact.
Could you please upload the latest versions of your API to maven central ?

Thanks

Regards
