### ISSUE TITLE
MailjetSocketTimeoutException

### ISSUE THREAD

**Issue by afimuc** [mailjet/mailjet-apiv3-java#88]
We're using the v3.1 API (mailjet-client-4.1.1.jar) to send e-mails from our application. This works fine when the application runs locally, but when deployed to our Red Hat Enterprise Server release 5.11 we always get a
`com.mailjet.client.errors.MailjetSocketTimeoutException: Socket Timeout
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:213) ~[mailjet-client-4.1.1.jar:?]`
after about 100ms.

Sending e-mails from the server console via curl to https://api.mailjet.com/v3.1/send works.

Any ideas why this could be or how to debug it?

**Comment by b1ack-ange1** [comment]
I have the same issue, this started a week ago. 90% of all letters doesn't sent anymore.
After update to actula version 4.1.1 problem not soved.
```
com.mailjet.client.errors.MailjetSocketTimeoutException: Socket Timeout
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:213) ~[mailjet-client-4.1.1.jar:na]
```

**Comment by afimuc** [comment]
In our case it was a permissions issue in the Tomcat configuration. Our catalina.policy would block our app from accessing api.mailjet.com

**Comment by farazdurrani** [comment]
Faced the same issue on Android. Simple lookup suggested to simple make a call on a new thread and that solved it.
