### ISSUE TITLE
Send Exception on HttpError

### ISSUE THREAD

**Issue by jbarotin** [mailjet/mailjet-apiv3-java#92]
The module should return Exception when http error code is different than 200. 

Write a `if(response.getStatus() != 200)` after each request execution is a bit cumcumber and definitely not a java way think. 

Do you mind if I send to PR in this way ?

**Comment by mskochev** [comment]
Hello jbarotin, what about the other success codes, i.e. 201 Created, 202 Accepted?

**Comment by jbarotin** [comment]
Yep, we can consider this. But exception for error code like 4XX and 5XX is a must have.

**Comment by mskochev** [comment]
The issue has been fixed as of the latest release v4.3.1 so I'm closing this thread.
