### ISSUE TITLE
Generate java bean in order than ressource object

### ISSUE THREAD

**Issue by jbarotin** [mailjet/mailjet-apiv3-java#93]
I saw the directory mailjet-apiv3-java/src/main/java/com/mailjet/client/resource/ I don't knwo where these files are coming from, but there are generated. 

It should very nice if in order of generating such files, you'll generate Java Bean, and with the use of librarie like [gson](https://github.com/google/gson), It will be easy to convert them to json or to create bean instance from json.

**Comment by systoyanov** [comment]
Hi @jbarotin ,

I'm part of the team responsible for the maintenance of the MailJet wrappers. Our current concept is to keep it as light as possible thus it is not planned to include bean definitions matching the API resources.

Regards,
Svetozar

**Comment by ddamyanova** [comment]
Hi @jbarotin ,

If your question was answered, please close this issue.

Thank you,
Desislava

**Comment by jbarotin** [comment]
Hi,

My question is answered, but my enquirie is still filled :). I convinced that adding bean will make your API easier to use. Anyway, I'll not make PR, so I close this issue for the momenet. I'll be back when I'll have to use MailJet API. 

See you,

Jérôme
