### ISSUE TITLE
NoClassDefFound on J2ee project

### ISSUE THREAD

**Issue by prism974** [mailjet/mailjet-apiv3-java#98]
Hello
I add in my pom.xml the dependency like this (i also tried the 4.0.5 version)

com.mailjet
mailjet-client
4.1.1
and my call is in a @stateless ejb

MailjetClient client = new MailjetClient(MJ_APIKEY_PUBLIC, MJ_APIKEY_PRIVATE);
Everything works fine in compilation
but at runtime i have an error
Caused by: java.lang.NoClassDefFoundError: com/mailjet/client/MailjetClient

**Comment by ddamyanova** [comment]
Hi @prism974 ,

Could you give us a little more context on your issue? You could attach your pom.xml and the class that creates the MailjetClient.

Regards,
Desislava

**Comment by mskochev** [comment]
Closing this issue due to its age.
