### ISSUE TITLE
Latest releases are not available on maven repo

### ISSUE THREAD

**Issue by osigida** [mailjet/mailjet-apiv3-java#99]
Releases 4.2 and higher are not available on maven central
lates release there is 4.1.1: https://search.maven.org/search?q=a:mailjet-client

**Comment by svenfrauen** [comment]
I noticed this too. Mailjet team, could you please provide the newest version on Maven Central.

**Comment by osigida** [comment]
Hi! any progress on publishing libs?

**Comment by Thoradin89** [comment]
Hello @osigida , @svenfrauen ,

We're working on releasing the latest version of the wrapper on Maven Central. 

Regards,
T.

**Comment by angelov-todor** [comment]
Do we have ETA on Maven Central?

**Comment by Nikola-Andreev** [comment]
Hello.
The latest version (4.2.0) is now published and visible in the central maven repository.
Sorry about the delay.
Regards.
